// packages/vue/src/components/ui/radio-group/RadioGroupItem.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { CheckIcon } from "@radix-icons/vue"
import {
	RadioGroupIndicator,
	RadioGroupItem,
	useForwardProps,
	type RadioGroupItemProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<RadioGroupItemProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<RadioGroupItem
		v-bind="forwardedProps"
		:class="
			cn(
				'border-primary text-primary focus-visible:ring-ring aspect-square h-4 w-4 rounded-full border shadow focus:outline-none focus-visible:ring-1 disabled:cursor-not-allowed disabled:opacity-50',
				props.class
			)
		"
	>
		<RadioGroupIndicator class="flex items-center justify-center">
			<CheckIcon class="fill-primary h-3.5 w-3.5" />
		</RadioGroupIndicator>
	</RadioGroupItem>
</template>

// packages/svelte/src/lib/components/ui/radio-group/radio-group-item.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { RadioGroup as RadioGroupPrimitive } from "bits-ui"
	import Check from "svelte-radix/Check.svelte"

	type $$Props = RadioGroupPrimitive.ItemProps & {
		value: string
	}
	type $$Events = RadioGroupPrimitive.ItemEvents

	let className: $$Props["class"] = undefined
	export let value: $$Props["value"]
	export { className as class }
</script>

<RadioGroupPrimitive.Item
	{value}
	class={cn(
		"border-primary text-primary focus-visible:ring-ring aspect-square h-4 w-4 rounded-full border shadow focus:outline-none focus-visible:ring-1 disabled:cursor-not-allowed disabled:opacity-50",
		className
	)}
	{...$$restProps}
	on:click
>
	<div class="flex items-center justify-center">
		<RadioGroupPrimitive.ItemIndicator>
			<Check class="fill-primary h-3.5 w-3.5" />
		</RadioGroupPrimitive.ItemIndicator>
	</div>
</RadioGroupPrimitive.Item>
