// packages/vue/src/components/ui/toggle-group/ToggleGroup.vue
<script setup lang="ts">
import type { toggleVariants } from "@/components/ui/toggle"
import { cn } from "@/lib/utils"
import type { VariantProps } from "class-variance-authority"
import {
	ToggleGroupRoot,
	useForwardPropsEmits,
	type ToggleGroupRootEmits,
	type ToggleGroupRootProps
} from "radix-vue"
import { computed, provide, type HTMLAttributes } from "vue"

type ToggleGroupVariants = VariantProps<typeof toggleVariants>

const props = defineProps<
	ToggleGroupRootProps & {
		class?: HTMLAttributes["class"]
		variant?: ToggleGroupVariants["variant"]
		size?: ToggleGroupVariants["size"]
	}
>()
const emits = defineEmits<ToggleGroupRootEmits>()

provide("toggleGroup", {
	variant: props.variant,
	size: props.size
})

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props
	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<ToggleGroupRoot
		v-bind="forwarded"
		:class="cn('flex items-center justify-center gap-1', props.class)"
	>
		<slot />
	</ToggleGroupRoot>
</template>

// packages/svelte/src/lib/components/ui/toggle-group/toggle-group.svelte
<script lang="ts">
	import type { toggleVariants } from "$lib/components/ui/toggle/index.js"
	import { cn } from "$lib/utils.js"
	import { ToggleGroup as ToggleGroupPrimitive } from "bits-ui"
	import type { VariantProps } from "tailwind-variants"
	import { setToggleGroupCtx } from "./index.js"

	type T = $$Generic<"single" | "multiple">
	type $$Props = ToggleGroupPrimitive.Props<T> & VariantProps<typeof toggleVariants>

	let className: string | undefined | null = undefined
	export { className as class }
	export let variant: $$Props["variant"] = "default"
	export let size: $$Props["size"] = "default"
	export let value: $$Props["value"] = undefined

	setToggleGroupCtx({
		variant,
		size
	})
</script>

<ToggleGroupPrimitive.Root
	class={cn("flex items-center justify-center gap-1", className)}
	bind:value
	{...$$restProps}
	let:builder
>
	<slot {builder} />
</ToggleGroupPrimitive.Root>
