// packages/vue/src/components/ui/toggle-group/ToggleGroupItem.vue
<script setup lang="ts">
import { toggleVariants } from "@/components/ui/toggle"
import { cn } from "@/lib/utils"
import type { VariantProps } from "class-variance-authority"
import { ToggleGroupItem, useForwardProps, type ToggleGroupItemProps } from "radix-vue"
import { computed, inject, type HTMLAttributes } from "vue"

type ToggleGroupVariants = VariantProps<typeof toggleVariants>

const props = defineProps<
	ToggleGroupItemProps & {
		class?: HTMLAttributes["class"]
		variant?: ToggleGroupVariants["variant"]
		size?: ToggleGroupVariants["size"]
	}
>()

const context = inject<ToggleGroupVariants>("toggleGroup")

const delegatedProps = computed(() => {
	const { class: _, variant, size, ...delegated } = props
	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<ToggleGroupItem
		v-bind="forwardedProps"
		:class="
			cn(
				toggleVariants({
					variant: context?.variant || variant,
					size: context?.size || size
				}),
				props.class
			)
		"
	>
		<slot />
	</ToggleGroupItem>
</template>

// packages/svelte/src/lib/components/ui/toggle-group/toggle-group-item.svelte
<script lang="ts">
	import { toggleVariants } from "$lib/components/ui/toggle/index.js"
	import { cn } from "$lib/utils.js"
	import { ToggleGroup as ToggleGroupPrimitive } from "bits-ui"
	import { getToggleGroupCtx, type ToggleVariants } from "./index.js"

	type $$Props = ToggleGroupPrimitive.ItemProps & ToggleVariants

	let className: string | undefined | null = undefined

	export { className as class }
	export let variant: $$Props["variant"] = "default"
	export let size: $$Props["size"] = "default"
	export let value: $$Props["value"]

	const ctx = getToggleGroupCtx()
</script>

<ToggleGroupPrimitive.Item
	class={cn(
		toggleVariants({
			variant: ctx.variant || variant,
			size: ctx.size || size
		}),
		className
	)}
	{value}
	{...$$restProps}
>
	<slot />
</ToggleGroupPrimitive.Item>
