// packages/svelte/src/lib/components/ui/scroll-area/scroll-area.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { ScrollArea as ScrollAreaPrimitive } from "bits-ui"
	import { Scrollbar } from "./index.js"

	type $$Props = ScrollAreaPrimitive.Props & {
		orientation?: "vertical" | "horizontal" | "both"
		scrollbarXClasses?: string
		scrollbarYClasses?: string
	}

	let className: $$Props["class"] = undefined
	export { className as class }
	export let orientation = "vertical"
	export let scrollbarXClasses: string = ""
	export let scrollbarYClasses: string = ""
</script>

<ScrollAreaPrimitive.Root {...$$restProps} class={cn("relative overflow-hidden", className)}>
	<ScrollAreaPrimitive.Viewport class="h-full w-full rounded-[inherit]">
		<ScrollAreaPrimitive.Content>
			<slot />
		</ScrollAreaPrimitive.Content>
	</ScrollAreaPrimitive.Viewport>
	{#if orientation === "vertical" || orientation === "both"}
		<Scrollbar orientation="vertical" class={scrollbarYClasses} />
	{/if}
	{#if orientation === "horizontal" || orientation === "both"}
		<Scrollbar orientation="horizontal" class={scrollbarXClasses} />
	{/if}
	<ScrollAreaPrimitive.Corner />
</ScrollAreaPrimitive.Root>

// packages/vue/src/components/ui/scroll-area/ScrollArea.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import {
	ScrollAreaCorner,
	ScrollAreaRoot,
	ScrollAreaViewport,
	type ScrollAreaRootProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"
import ScrollBar from "./ScrollBar.vue"

const props = defineProps<ScrollAreaRootProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<ScrollAreaRoot v-bind="delegatedProps" :class="cn('relative overflow-hidden', props.class)">
		<ScrollAreaViewport class="h-full w-full rounded-[inherit]">
			<slot />
		</ScrollAreaViewport>
		<ScrollBar />
		<ScrollAreaCorner />
	</ScrollAreaRoot>
</template>
