// packages/vue/src/components/ui/command/CommandGroup.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { ComboboxGroupProps } from "radix-vue"
import { ComboboxGroup, ComboboxLabel } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<
	ComboboxGroupProps & {
		class?: HTMLAttributes["class"]
		heading?: string
	}
>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<ComboboxGroup
		v-bind="delegatedProps"
		:class="
			cn(
				'text-foreground [&_[cmdk-group-heading]]:text-muted-foreground overflow-hidden p-1 [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-xs [&_[cmdk-group-heading]]:font-medium',
				props.class
			)
		"
	>
		<ComboboxLabel v-if="heading" class="text-muted-foreground px-2 py-1.5 text-xs font-medium">
			{{ heading }}
		</ComboboxLabel>
		<slot />
	</ComboboxGroup>
</template>

// packages/svelte/src/lib/components/ui/command/command-group.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Command as CommandPrimitive } from "cmdk-sv"

	type $$Props = CommandPrimitive.GroupProps

	let className: string | undefined | null = undefined
	export { className as class }
</script>

<CommandPrimitive.Group
	class={cn(
		"text-foreground [&_[data-cmdk-group-heading]]:text-muted-foreground overflow-hidden p-1 [&_[data-cmdk-group-heading]]:px-2 [&_[data-cmdk-group-heading]]:py-1.5 [&_[data-cmdk-group-heading]]:text-xs [&_[data-cmdk-group-heading]]:font-medium",
		className
	)}
	{...$$restProps}
>
	<slot />
</CommandPrimitive.Group>
