// packages/svelte/src/lib/components/ui/sheet/sheet-description.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Dialog as SheetPrimitive } from "bits-ui"

	type $$Props = SheetPrimitive.DescriptionProps

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<SheetPrimitive.Description class={cn("text-muted-foreground text-sm", className)} {...$$restProps}>
	<slot />
</SheetPrimitive.Description>

// packages/vue/src/components/ui/sheet/SheetDescription.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DialogDescription, type DialogDescriptionProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<DialogDescriptionProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<DialogDescription
		:class="cn('text-muted-foreground text-sm', props.class)"
		v-bind="delegatedProps"
	>
		<slot />
	</DialogDescription>
</template>
