// packages/svelte/src/lib/components/ui/sheet/sheet-content.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Dialog as SheetPrimitive } from "bits-ui"
	import Cross2 from "svelte-radix/Cross2.svelte"
	import { fly } from "svelte/transition"
	import { SheetOverlay, SheetPortal, sheetTransitions, sheetVariants, type Side } from "./index.js"

	type $$Props = SheetPrimitive.ContentProps & {
		side?: Side
	}

	let className: $$Props["class"] = undefined
	export let side: $$Props["side"] = "right"
	export { className as class }
	export let inTransition: $$Props["inTransition"] = fly
	export let inTransitionConfig: $$Props["inTransitionConfig"] =
		sheetTransitions[side ?? "right"].in
	export let outTransition: $$Props["outTransition"] = fly
	export let outTransitionConfig: $$Props["outTransitionConfig"] =
		sheetTransitions[side ?? "right"].out
</script>

<SheetPortal>
	<SheetOverlay />
	<SheetPrimitive.Content
		{inTransition}
		{inTransitionConfig}
		{outTransition}
		{outTransitionConfig}
		class={cn(sheetVariants({ side }), className)}
		{...$$restProps}
	>
		<slot />
		<SheetPrimitive.Close
			class="ring-offset-background focus:ring-ring data-[state=open]:bg-secondary absolute right-4 top-4 rounded-sm opacity-70 transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:pointer-events-none"
		>
			<Cross2 class="h-4 w-4" />
			<span class="sr-only">Close</span>
		</SheetPrimitive.Close>
	</SheetPrimitive.Content>
</SheetPortal>

// packages/vue/src/components/ui/sheet/SheetContent.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { Cross2Icon } from "@radix-icons/vue"
import {
	DialogClose,
	DialogContent,
	DialogOverlay,
	DialogPortal,
	useForwardPropsEmits,
	type DialogContentEmits,
	type DialogContentProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"
import { sheetVariants, type SheetVariants } from "."

interface SheetContentProps extends DialogContentProps {
	class?: HTMLAttributes["class"]
	side?: SheetVariants["side"]
}

defineOptions({
	inheritAttrs: false
})

const props = defineProps<SheetContentProps>()

const emits = defineEmits<DialogContentEmits>()

const delegatedProps = computed(() => {
	const { class: _, side, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<DialogPortal>
		<DialogOverlay
			class="data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 fixed inset-0 z-50 bg-black/80"
		/>
		<DialogContent
			:class="cn(sheetVariants({ side }), props.class)"
			v-bind="{ ...forwarded, ...$attrs }"
		>
			<slot />

			<DialogClose
				class="ring-offset-background focus:ring-ring data-[state=open]:bg-secondary absolute right-4 top-4 rounded-sm opacity-70 transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:pointer-events-none"
			>
				<Cross2Icon class="h-4 w-4" />
			</DialogClose>
		</DialogContent>
	</DialogPortal>
</template>
