// packages/svelte/src/lib/components/ui/sheet/sheet-title.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Dialog as SheetPrimitive } from "bits-ui"

	type $$Props = SheetPrimitive.TitleProps

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<SheetPrimitive.Title
	class={cn("text-foreground text-lg font-semibold", className)}
	{...$$restProps}
>
	<slot />
</SheetPrimitive.Title>

// packages/vue/src/components/ui/sheet/SheetTitle.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DialogTitle, type DialogTitleProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<DialogTitleProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<DialogTitle
		:class="cn('text-foreground text-lg font-semibold', props.class)"
		v-bind="delegatedProps"
	>
		<slot />
	</DialogTitle>
</template>
