// packages/svelte5/src/lib/components/ui/sheet/sheet-title.svelte
<script lang="ts">
	import { Dialog as SheetPrimitive } from "bits-ui";
	import { cn } from "@kksh/svelte5/utils.ts";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: SheetPrimitive.TitleProps = $props();
</script>

<SheetPrimitive.Title
	bind:ref
	class={cn("text-foreground text-lg font-semibold", className)}
	{...restProps}
/>

// packages/vue/src/components/ui/sheet/SheetTitle.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DialogTitle, type DialogTitleProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<DialogTitleProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<DialogTitle
		:class="cn('text-foreground text-lg font-semibold', props.class)"
		v-bind="delegatedProps"
	>
		<slot />
	</DialogTitle>
</template>
