// packages/svelte5/src/lib/components/ui/tabs/tabs-list.svelte
<script lang="ts">
	import { Tabs as TabsPrimitive } from "bits-ui";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: TabsPrimitive.ListProps = $props();
</script>

<TabsPrimitive.List
	bind:ref
	class={cn(
		"bg-muted text-muted-foreground inline-flex h-9 items-center justify-center rounded-lg p-1",
		className
	)}
	{...restProps}
/>

// packages/vue/src/components/ui/tabs/TabsList.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { TabsList, type TabsListProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<TabsListProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<TabsList
		v-bind="delegatedProps"
		:class="
			cn(
				'bg-muted text-muted-foreground inline-flex h-9 items-center justify-center rounded-lg p-1',
				props.class
			)
		"
	>
		<slot />
	</TabsList>
</template>
