// packages/svelte5/src/lib/components/ui/dialog/dialog-title.svelte
<script lang="ts">
	import { Dialog as DialogPrimitive } from "bits-ui";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: DialogPrimitive.TitleProps = $props();
</script>

<DialogPrimitive.Title
	bind:ref
	class={cn("text-lg font-semibold leading-none tracking-tight", className)}
	{...restProps}
/>

// packages/vue/src/components/ui/dialog/DialogTitle.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DialogTitle, useForwardProps, type DialogTitleProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<DialogTitleProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<DialogTitle
		v-bind="forwardedProps"
		:class="cn('text-lg font-semibold leading-none tracking-tight', props.class)"
	>
		<slot />
	</DialogTitle>
</template>
