// packages/vue/src/components/ui/alert-dialog/AlertDialogDescription.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { AlertDialogDescription, type AlertDialogDescriptionProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<AlertDialogDescriptionProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<AlertDialogDescription
		v-bind="delegatedProps"
		:class="cn('text-muted-foreground text-sm', props.class)"
	>
		<slot />
	</AlertDialogDescription>
</template>

// packages/svelte/src/lib/components/ui/alert-dialog/alert-dialog-description.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { AlertDialog as AlertDialogPrimitive } from "bits-ui"

	type $$Props = AlertDialogPrimitive.DescriptionProps

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<AlertDialogPrimitive.Description
	class={cn("text-muted-foreground text-sm", className)}
	{...$$restProps}
>
	<slot />
</AlertDialogPrimitive.Description>
