// packages/svelte/src/lib/components/ui/calendar/calendar-head-cell.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Calendar as CalendarPrimitive } from "bits-ui"

	type $$Props = CalendarPrimitive.HeadCellProps

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<CalendarPrimitive.HeadCell
	class={cn("text-muted-foreground w-8 rounded-md text-[0.8rem] font-normal", className)}
	{...$$restProps}
>
	<slot />
</CalendarPrimitive.HeadCell>

// packages/vue/src/components/ui/calendar/CalendarHeadCell.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { CalendarHeadCell, useForwardProps, type CalendarHeadCellProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<CalendarHeadCellProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<CalendarHeadCell
		:class="cn('text-muted-foreground w-8 rounded-md text-[0.8rem] font-normal', props.class)"
		v-bind="forwardedProps"
	>
		<slot />
	</CalendarHeadCell>
</template>
