// packages/svelte/src/lib/components/ui/calendar/calendar-cell.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Calendar as CalendarPrimitive } from "bits-ui"

	type $$Props = CalendarPrimitive.CellProps

	export let date: $$Props["date"]
	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<CalendarPrimitive.Cell
	{date}
	class={cn(
		"[&:has([data-selected])]:bg-accent [&:has([data-selected][data-outside-month])]:bg-accent/50 relative p-0 text-center text-sm focus-within:relative focus-within:z-20 [&:has([data-selected])]:rounded-md",
		className
	)}
	{...$$restProps}
>
	<slot />
</CalendarPrimitive.Cell>

// packages/vue/src/components/ui/calendar/CalendarCell.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { CalendarCell, useForwardProps, type CalendarCellProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<CalendarCellProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<CalendarCell
		:class="
			cn(
				'[&:has([data-selected])]:bg-accent [&:has([data-selected][data-outside-view])]:bg-accent/50 relative p-0 text-center text-sm focus-within:relative focus-within:z-20 [&:has([data-selected])]:rounded-md',
				props.class
			)
		"
		v-bind="forwardedProps"
	>
		<slot />
	</CalendarCell>
</template>
