// packages/svelte/src/lib/components/ui/calendar/calendar-heading.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Calendar as CalendarPrimitive } from "bits-ui"

	type $$Props = CalendarPrimitive.HeadingProps

	let className: string | undefined | null = undefined
	export { className as class }
</script>

<CalendarPrimitive.Heading
	let:headingValue
	class={cn("text-sm font-medium", className)}
	{...$$restProps}
>
	<slot {headingValue}>
		{headingValue}
	</slot>
</CalendarPrimitive.Heading>

// packages/vue/src/components/ui/calendar/CalendarHeading.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { CalendarHeading, useForwardProps, type CalendarHeadingProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<CalendarHeadingProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<CalendarHeading
		v-slot="{ headingValue }"
		:class="cn('text-sm font-medium', props.class)"
		v-bind="forwardedProps"
	>
		<slot :heading-value>
			{{ headingValue }}
		</slot>
	</CalendarHeading>
</template>
