// packages/svelte/src/lib/components/ui/carousel/carousel-previous.svelte
<script lang="ts">
	import { Button, type buttonVariants, type Props } from "$lib/components/ui/button/index.js"
	import { cn } from "$lib/utils.js"
	import ArrowLeft from "svelte-radix/ArrowLeft.svelte"
	import type { VariantProps } from "tailwind-variants"
	import { getEmblaContext } from "./context.js"

	type $$Props = Props

	let className: $$Props["class"] = undefined
	export { className as class }
	export let variant: VariantProps<typeof buttonVariants>["variant"] = "outline"
	export let size: VariantProps<typeof buttonVariants>["size"] = "icon"

	const { orientation, canScrollPrev, scrollPrev, handleKeyDown } =
		getEmblaContext("<Carousel.Previous/>")
</script>

<Button
	{variant}
	{size}
	class={cn(
		"absolute h-8 w-8 touch-manipulation rounded-full",
		$orientation === "horizontal"
			? "-left-12 top-1/2 -translate-y-1/2"
			: "-top-12 left-1/2 -translate-x-1/2 rotate-90",
		className
	)}
	disabled={!$canScrollPrev}
	on:click={scrollPrev}
	on:keydown={handleKeyDown}
	{...$$restProps}
>
	<ArrowLeft class="h-4 w-4" />
	<span class="sr-only">Previous slide</span>
</Button>

// packages/vue/src/components/ui/carousel/CarouselPrevious.vue
<script setup lang="ts">
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { ArrowLeftIcon } from "@radix-icons/vue"
import type { WithClassAsProps } from "./interface"
import { useCarousel } from "./useCarousel"

const props = defineProps<WithClassAsProps>()

const { orientation, canScrollPrev, scrollPrev } = useCarousel()
</script>

<template>
	<Button
		:disabled="!canScrollPrev"
		:class="
			cn(
				'absolute h-8 w-8 touch-manipulation rounded-full p-0',
				orientation === 'horizontal'
					? '-left-12 top-1/2 -translate-y-1/2'
					: '-top-12 left-1/2 -translate-x-1/2 rotate-90',
				props.class
			)
		"
		variant="outline"
		@click="scrollPrev"
	>
		<slot>
			<ArrowLeftIcon class="h-4 w-4 text-current" />
			<span class="sr-only">Previous Slide</span>
		</slot>
	</Button>
</template>
