// packages/vue/src/components/ui/slider/Slider.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { SliderRootEmits, SliderRootProps } from "radix-vue"
import { SliderRange, SliderRoot, SliderThumb, SliderTrack, useForwardPropsEmits } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<SliderRootProps & { class?: HTMLAttributes["class"] }>()
const emits = defineEmits<SliderRootEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<SliderRoot
		:class="cn('relative flex w-full touch-none select-none items-center', props.class)"
		v-bind="forwarded"
	>
		<SliderTrack class="bg-primary/20 relative h-1.5 w-full grow overflow-hidden rounded-full">
			<SliderRange class="bg-primary absolute h-full" />
		</SliderTrack>
		<SliderThumb
			v-for="(_, key) in modelValue"
			:key="key"
			class="border-primary bg-background ring-offset-background focus-visible:ring-ring block h-5 w-5 rounded-full border-2 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
		/>
	</SliderRoot>
</template>

// packages/svelte/src/lib/components/ui/slider/slider.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Slider as SliderPrimitive } from "bits-ui"

	type $$Props = SliderPrimitive.Props

	let className: $$Props["class"] = undefined
	export let value: $$Props["value"] = [0]
	export { className as class }
</script>

<SliderPrimitive.Root
	bind:value
	class={cn("relative flex w-full touch-none select-none items-center", className)}
	{...$$restProps}
	let:thumbs
>
	<span class="bg-primary/20 relative h-1.5 w-full grow overflow-hidden rounded-full">
		<SliderPrimitive.Range class="bg-primary absolute h-full" />
	</span>
	{#each thumbs as thumb}
		<SliderPrimitive.Thumb
			{thumb}
			class="border-primary/50 bg-background focus-visible:ring-ring block h-4 w-4 rounded-full border shadow transition-colors focus-visible:outline-none focus-visible:ring-1 disabled:pointer-events-none disabled:opacity-50"
		/>
	{/each}
</SliderPrimitive.Root>
