// packages/vue/src/components/ui/textarea/Textarea.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { useVModel } from "@vueuse/core"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
	defaultValue?: string | number
	modelValue?: string | number
}>()

const emits = defineEmits<{
	(e: "update:modelValue", payload: string | number): void
}>()

const modelValue = useVModel(props, "modelValue", emits, {
	passive: true,
	defaultValue: props.defaultValue
})
</script>

<template>
	<textarea
		v-model="modelValue"
		:class="
			cn(
				'border-input placeholder:text-muted-foreground focus-visible:ring-ring flex min-h-[60px] w-full rounded-md border bg-transparent px-3 py-2 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 disabled:cursor-not-allowed disabled:opacity-50',
				props.class
			)
		"
	/>
</template>

// packages/svelte/src/lib/components/ui/textarea/textarea.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLTextareaAttributes } from "svelte/elements"
	import type { TextareaEvents } from "./index.js"

	type $$Props = HTMLTextareaAttributes
	type $$Events = TextareaEvents

	let className: $$Props["class"] = undefined
	export let value: $$Props["value"] = undefined
	export { className as class }

	// Workaround for https://github.com/sveltejs/svelte/issues/9305
	// Fixed in Svelte 5, but not backported to 4.x.
	export let readonly: $$Props["readonly"] = undefined
</script>

<textarea
	class={cn(
		"border-input placeholder:text-muted-foreground focus-visible:ring-ring flex min-h-[60px] w-full rounded-md border bg-transparent px-3 py-2 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 disabled:cursor-not-allowed disabled:opacity-50",
		className
	)}
	bind:value
	{readonly}
	on:blur
	on:change
	on:click
	on:focus
	on:keydown
	on:keypress
	on:keyup
	on:mouseover
	on:mouseenter
	on:mouseleave
	on:paste
	on:input
	{...$$restProps}
></textarea>
