// packages/vue/src/components/ui/pagination/PaginationEllipsis.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DotsHorizontalIcon } from "@radix-icons/vue"
import { PaginationEllipsis, type PaginationEllipsisProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<PaginationEllipsisProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<PaginationEllipsis
		v-bind="delegatedProps"
		:class="cn('flex h-9 w-9 items-center justify-center', props.class)"
	>
		<slot>
			<DotsHorizontalIcon />
		</slot>
	</PaginationEllipsis>
</template>

// packages/svelte/src/lib/components/ui/pagination/pagination-ellipsis.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import DotsHorizontal from "svelte-radix/DotsHorizontal.svelte"
	import type { HTMLAttributes } from "svelte/elements"

	type $$Props = HTMLAttributes<HTMLSpanElement>

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<span
	aria-hidden
	class={cn("flex h-9 w-9 items-center justify-center", className)}
	{...$$restProps}
>
	<DotsHorizontal class="h-4 w-4" />
	<span class="sr-only">More pages</span>
</span>
