// packages/vue/src/components/ui/dropdown-menu/DropdownMenuLabel.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DropdownMenuLabel, useForwardProps, type DropdownMenuLabelProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<
	DropdownMenuLabelProps & { class?: HTMLAttributes["class"]; inset?: boolean }
>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<DropdownMenuLabel
		v-bind="forwardedProps"
		:class="cn('px-2 py-1.5 text-sm font-semibold', inset && 'pl-8', props.class)"
	>
		<slot />
	</DropdownMenuLabel>
</template>

// packages/svelte5/src/lib/components/ui/dropdown-menu/dropdown-menu-label.svelte
<script lang="ts">
	import { cn } from "@kksh/svelte5/utils.js";
	import { type WithElementRef } from "bits-ui";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		inset,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		inset?: boolean;
	} = $props();
</script>

<div
	bind:this={ref}
	class={cn("px-2 py-1.5 text-sm font-semibold", inset && "pl-8", className)}
	{...restProps}
>
	{@render children?.()}
</div>
