// packages/vue/src/components/ui/dropdown-menu/DropdownMenuItem.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DropdownMenuItem, useForwardProps, type DropdownMenuItemProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<
	DropdownMenuItemProps & { class?: HTMLAttributes["class"]; inset?: boolean }
>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<DropdownMenuItem
		v-bind="forwardedProps"
		:class="
			cn(
				'focus:bg-accent focus:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none transition-colors data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
				inset && 'pl-8',
				props.class
			)
		"
	>
		<slot />
	</DropdownMenuItem>
</template>

// packages/svelte5/src/lib/components/ui/dropdown-menu/dropdown-menu-item.svelte
<script lang="ts">
	import { cn } from "@kksh/svelte5/utils.ts";
	import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";

	let {
		ref = $bindable(null),
		class: className,
		inset,
		...restProps
	}: DropdownMenuPrimitive.ItemProps & {
		inset?: boolean;
	} = $props();
</script>

<DropdownMenuPrimitive.Item
	bind:ref
	class={cn(
		"data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground relative flex cursor-default select-none items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none transition-colors data-[disabled]:pointer-events-none data-[disabled]:opacity-50 [&>svg]:size-4 [&>svg]:shrink-0",
		inset && "pl-8",
		className
	)}
	{...restProps}
/>
