// packages/svelte/src/lib/components/ui/alert/alert.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLAttributes } from "svelte/elements"
	import { alertVariants, type Variant } from "./index.js"

	type $$Props = HTMLAttributes<HTMLDivElement> & {
		variant?: Variant
	}

	let className: $$Props["class"] = undefined
	export let variant: $$Props["variant"] = "default"
	export { className as class }
</script>

<div class={cn(alertVariants({ variant }), className)} {...$$restProps} role="alert">
	<slot />
</div>

// packages/vue/src/components/ui/alert/Alert.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"
import { alertVariants, type AlertVariants } from "."

const props = defineProps<{
	class?: HTMLAttributes["class"]
	variant?: AlertVariants["variant"]
}>()
</script>

<template>
	<div :class="cn(alertVariants({ variant }), props.class)" role="alert">
		<slot />
	</div>
</template>
