// packages/svelte5/src/lib/components/ui/resizable/resizable-handle.svelte
<script lang="ts">
	import DragHandleDots2 from "svelte-radix/DragHandleDots2.svelte";
	import * as ResizablePrimitive from "paneforge";
	import type { WithoutChildrenOrChild } from "bits-ui";
	import { cn } from "@kksh/svelte5/utils.ts";

	let {
		ref = $bindable(null),
		class: className,
		withHandle = false,
		...restProps
	}: WithoutChildrenOrChild<ResizablePrimitive.PaneResizerProps> & {
		withHandle?: boolean;
	} = $props();
</script>

<ResizablePrimitive.PaneResizer
	bind:ref
	class={cn(
		"bg-border focus-visible:ring-ring relative flex w-px items-center justify-center after:absolute after:inset-y-0 after:left-1/2 after:w-1 after:-translate-x-1/2 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-offset-1 data-[direction=vertical]:h-px data-[direction=vertical]:w-full data-[direction=vertical]:after:left-0 data-[direction=vertical]:after:h-1 data-[direction=vertical]:after:w-full data-[direction=vertical]:after:-translate-y-1/2 data-[direction=vertical]:after:translate-x-0 [&[data-direction=vertical]>div]:rotate-90",
		className
	)}
	{...restProps}
>
	{#if withHandle}
		<div class="bg-border z-10 flex h-4 w-3 items-center justify-center rounded-sm border">
			<DragHandleDots2 class="size-2.5" />
		</div>
	{/if}
</ResizablePrimitive.PaneResizer>

// packages/vue/src/components/ui/resizable/ResizableHandle.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DragHandleDots2Icon } from "@radix-icons/vue"
import {
	SplitterResizeHandle,
	useForwardPropsEmits,
	type SplitterResizeHandleEmits,
	type SplitterResizeHandleProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<
	SplitterResizeHandleProps & { class?: HTMLAttributes["class"]; withHandle?: boolean }
>()
const emits = defineEmits<SplitterResizeHandleEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props
	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<SplitterResizeHandle
		v-bind="forwarded"
		:class="
			cn(
				'bg-border focus-visible:ring-ring relative flex w-px items-center justify-center after:absolute after:inset-y-0 after:left-1/2 after:w-1 after:-translate-x-1/2 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-offset-1 [&[data-orientation=vertical]>div]:rotate-90 [&[data-orientation=vertical]]:h-px [&[data-orientation=vertical]]:w-full [&[data-orientation=vertical]]:after:left-0 [&[data-orientation=vertical]]:after:h-1 [&[data-orientation=vertical]]:after:w-full [&[data-orientation=vertical]]:after:-translate-y-1/2 [&[data-orientation=vertical]]:after:translate-x-0',
				props.class
			)
		"
	>
		<template v-if="props.withHandle">
			<div class="bg-border z-10 flex h-4 w-3 items-center justify-center rounded-sm border">
				<DragHandleDots2Icon class="h-2.5 w-2.5" />
			</div>
		</template>
	</SplitterResizeHandle>
</template>
