// packages/vue/src/components/ui/carousel/CarouselPrevious.vue
<script setup lang="ts">
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { ArrowLeftIcon } from "@radix-icons/vue"
import type { WithClassAsProps } from "./interface"
import { useCarousel } from "./useCarousel"

const props = defineProps<WithClassAsProps>()

const { orientation, canScrollPrev, scrollPrev } = useCarousel()
</script>

<template>
	<Button
		:disabled="!canScrollPrev"
		:class="
			cn(
				'absolute h-8 w-8 touch-manipulation rounded-full p-0',
				orientation === 'horizontal'
					? '-left-12 top-1/2 -translate-y-1/2'
					: '-top-12 left-1/2 -translate-x-1/2 rotate-90',
				props.class
			)
		"
		variant="outline"
		@click="scrollPrev"
	>
		<slot>
			<ArrowLeftIcon class="h-4 w-4 text-current" />
			<span class="sr-only">Previous Slide</span>
		</slot>
	</Button>
</template>

// packages/svelte5/src/lib/components/ui/carousel/carousel-previous.svelte
<script lang="ts">
	import ArrowLeft from "svelte-radix/ArrowLeft.svelte";
	import type { WithoutChildren } from "bits-ui";
	import { getEmblaContext } from "./context.js";
	import { cn } from "@kksh/svelte5/utils.js";
	import { Button, type Props } from "@kksh/svelte5/components/ui/button/index.js";

	let {
		ref = $bindable(null),
		class: className,
		variant = "outline",
		size = "icon",
		...restProps
	}: WithoutChildren<Props> = $props();

	const emblaCtx = getEmblaContext("<Carousel.Previous/>");
</script>

<Button
	{variant}
	{size}
	class={cn(
		"absolute size-8 touch-manipulation rounded-full",
		emblaCtx.orientation === "horizontal"
			? "-left-12 top-1/2 -translate-y-1/2"
			: "-top-12 left-1/2 -translate-x-1/2 rotate-90",
		className
	)}
	disabled={!emblaCtx.canScrollPrev}
	onclick={emblaCtx.scrollPrev}
	onkeydown={emblaCtx.handleKeyDown}
	{...restProps}
	bind:ref
>
	<ArrowLeft class="size-4" />
	<span class="sr-only">Previous slide</span>
</Button>
