// packages/vue/src/components/ui/accordion/AccordionTrigger.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { ChevronDownIcon } from "@radix-icons/vue"
import { AccordionHeader, AccordionTrigger, type AccordionTriggerProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<AccordionTriggerProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<AccordionHeader class="flex">
		<AccordionTrigger
			v-bind="delegatedProps"
			:class="
				cn(
					'flex flex-1 items-center justify-between py-4 text-sm font-medium transition-all hover:underline [&[data-state=open]>svg]:rotate-180',
					props.class
				)
			"
		>
			<slot />
			<slot name="icon">
				<ChevronDownIcon
					class="text-muted-foreground h-4 w-4 shrink-0 transition-transform duration-200"
				/>
			</slot>
		</AccordionTrigger>
	</AccordionHeader>
</template>

// packages/svelte/src/lib/components/ui/accordion/accordion-trigger.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Accordion as AccordionPrimitive } from "bits-ui"
	import ChevronDown from "svelte-radix/ChevronDown.svelte"

	type $$Props = AccordionPrimitive.TriggerProps
	type $$Events = AccordionPrimitive.TriggerEvents

	let className: $$Props["class"] = undefined
	export let level: AccordionPrimitive.HeaderProps["level"] = 3
	export { className as class }
</script>

<AccordionPrimitive.Header {level} class="flex">
	<AccordionPrimitive.Trigger
		class={cn(
			"flex flex-1 items-center justify-between py-4 text-sm font-medium transition-all hover:underline [&[data-state=open]>svg]:rotate-180",
			className
		)}
		{...$$restProps}
		on:click
	>
		<slot />
		<ChevronDown class="text-muted-foreground h-4 w-4 shrink-0 transition-transform duration-200" />
	</AccordionPrimitive.Trigger>
</AccordionPrimitive.Header>
