// packages/vue/src/components/ui/dropdown-menu/DropdownMenuRadioItem.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DotFilledIcon } from "@radix-icons/vue"
import {
	DropdownMenuItemIndicator,
	DropdownMenuRadioItem,
	useForwardPropsEmits,
	type DropdownMenuRadioItemEmits,
	type DropdownMenuRadioItemProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<DropdownMenuRadioItemProps & { class?: HTMLAttributes["class"] }>()

const emits = defineEmits<DropdownMenuRadioItemEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<DropdownMenuRadioItem
		v-bind="forwarded"
		:class="
			cn(
				'focus:bg-accent focus:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none transition-colors data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
				props.class
			)
		"
	>
		<span class="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
			<DropdownMenuItemIndicator>
				<DotFilledIcon class="h-4 w-4 fill-current" />
			</DropdownMenuItemIndicator>
		</span>
		<slot />
	</DropdownMenuRadioItem>
</template>

// packages/svelte/src/lib/components/ui/dropdown-menu/dropdown-menu-radio-item.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui"
	import DotFilled from "svelte-radix/DotFilled.svelte"

	type $$Props = DropdownMenuPrimitive.RadioItemProps
	type $$Events = DropdownMenuPrimitive.RadioItemEvents

	let className: $$Props["class"] = undefined
	export let value: DropdownMenuPrimitive.RadioItemProps["value"]
	export { className as class }
</script>

<DropdownMenuPrimitive.RadioItem
	class={cn(
		"data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
		className
	)}
	{value}
	{...$$restProps}
	on:click
	on:keydown
	on:focusin
	on:focusout
	on:pointerdown
	on:pointerleave
	on:pointermove
>
	<span class="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
		<DropdownMenuPrimitive.RadioIndicator>
			<DotFilled class="h-4 w-4 fill-current" />
		</DropdownMenuPrimitive.RadioIndicator>
	</span>
	<slot />
</DropdownMenuPrimitive.RadioItem>
