// packages/vue/src/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { ChevronRightIcon } from "@radix-icons/vue"
import {
	DropdownMenuSubTrigger,
	useForwardProps,
	type DropdownMenuSubTriggerProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<DropdownMenuSubTriggerProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<DropdownMenuSubTrigger
		v-bind="forwardedProps"
		:class="
			cn(
				'focus:bg-accent data-[state=open]:bg-accent flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none',
				props.class
			)
		"
	>
		<slot />
		<ChevronRightIcon class="ml-auto h-4 w-4" />
	</DropdownMenuSubTrigger>
</template>

// packages/svelte/src/lib/components/ui/dropdown-menu/dropdown-menu-sub-trigger.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui"
	import ChevronRight from "svelte-radix/ChevronRight.svelte"

	type $$Props = DropdownMenuPrimitive.SubTriggerProps & {
		inset?: boolean
	}
	type $$Events = DropdownMenuPrimitive.SubTriggerEvents

	let className: $$Props["class"] = undefined
	export let inset: $$Props["inset"] = undefined
	export { className as class }
</script>

<DropdownMenuPrimitive.SubTrigger
	class={cn(
		"data-[highlighted]:bg-accent data-[state=open]:bg-accent data-[highlighted]:text-accent-foreground data-[state=open]:text-accent-foreground flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none",
		inset && "pl-8",
		className
	)}
	{...$$restProps}
	on:click
	on:keydown
	on:focusin
	on:focusout
	on:pointerleave
	on:pointermove
>
	<slot />
	<ChevronRight class="ml-auto h-4 w-4" />
</DropdownMenuPrimitive.SubTrigger>
