// packages/vue/src/components/ui/dropdown-menu/DropdownMenuItem.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DropdownMenuItem, useForwardProps, type DropdownMenuItemProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<
	DropdownMenuItemProps & { class?: HTMLAttributes["class"]; inset?: boolean }
>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<DropdownMenuItem
		v-bind="forwardedProps"
		:class="
			cn(
				'focus:bg-accent focus:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none transition-colors data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
				inset && 'pl-8',
				props.class
			)
		"
	>
		<slot />
	</DropdownMenuItem>
</template>

// packages/svelte/src/lib/components/ui/dropdown-menu/dropdown-menu-item.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui"

	type $$Props = DropdownMenuPrimitive.ItemProps & {
		inset?: boolean
	}
	type $$Events = DropdownMenuPrimitive.ItemEvents

	let className: $$Props["class"] = undefined
	export let inset: $$Props["inset"] = undefined
	export { className as class }
</script>

<DropdownMenuPrimitive.Item
	class={cn(
		"data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
		inset && "pl-8",
		className
	)}
	on:click
	on:keydown
	on:focusin
	on:focusout
	on:pointerdown
	on:pointerleave
	on:pointermove
	{...$$restProps}
>
	<slot />
</DropdownMenuPrimitive.Item>
