// packages/vue/src/components/ui/range-calendar/RangeCalendarGrid.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { RangeCalendarGrid, useForwardProps, type RangeCalendarGridProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<RangeCalendarGridProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<RangeCalendarGrid
		:class="cn('w-full border-collapse space-y-1', props.class)"
		v-bind="forwardedProps"
	>
		<slot />
	</RangeCalendarGrid>
</template>

// packages/svelte/src/lib/components/ui/range-calendar/range-calendar-grid.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { RangeCalendar as RangeCalendarPrimitive } from "bits-ui"

	type $$Props = RangeCalendarPrimitive.GridProps

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<RangeCalendarPrimitive.Grid
	class={cn("w-full border-collapse space-y-1", className)}
	{...$$restProps}
>
	<slot />
</RangeCalendarPrimitive.Grid>
