// packages/vue/src/components/ui/range-calendar/RangeCalendarHeading.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { RangeCalendarHeading, useForwardProps, type RangeCalendarHeadingProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<RangeCalendarHeadingProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<RangeCalendarHeading
		v-slot="{ headingValue }"
		:class="cn('text-sm font-medium', props.class)"
		v-bind="forwardedProps"
	>
		<slot :heading-value>
			{{ headingValue }}
		</slot>
	</RangeCalendarHeading>
</template>

// packages/svelte/src/lib/components/ui/range-calendar/range-calendar-heading.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { RangeCalendar as RangeCalendarPrimitive } from "bits-ui"

	type $$Props = RangeCalendarPrimitive.HeadingProps

	let className: string | undefined | null = undefined
	export { className as class }
</script>

<RangeCalendarPrimitive.Heading
	let:headingValue
	class={cn("text-sm font-medium", className)}
	{...$$restProps}
>
	<slot {headingValue}>
		{headingValue}
	</slot>
</RangeCalendarPrimitive.Heading>
