// packages/svelte/src/lib/components/ui/form/form-description.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import * as FormPrimitive from "formsnap"

	type $$Props = FormPrimitive.DescriptionProps
	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<FormPrimitive.Description
	class={cn("text-muted-foreground text-[0.8rem]", className)}
	{...$$restProps}
	let:descriptionAttrs
>
	<slot {descriptionAttrs} />
</FormPrimitive.Description>

// packages/vue/src/components/ui/form/FormDescription.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"
import { useFormField } from "./useFormField"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()

const { formDescriptionId } = useFormField()
</script>

<template>
	<p :id="formDescriptionId" :class="cn('text-muted-foreground text-sm', props.class)">
		<slot />
	</p>
</template>
