// packages/svelte/src/lib/components/ui/form/form-label.svelte
<script lang="ts">
	import { Label } from "$lib/components/ui/label/index.js"
	import { cn } from "$lib/utils.js"
	import type { Label as LabelPrimitive } from "bits-ui"
	import { getFormControl } from "formsnap"

	type $$Props = LabelPrimitive.Props

	let className: $$Props["class"] = undefined
	export { className as class }

	const { labelAttrs } = getFormControl()
</script>

<Label {...$labelAttrs} class={cn("data-[fs-error]:text-destructive", className)} {...$$restProps}>
	<slot {labelAttrs} />
</Label>

// packages/vue/src/components/ui/form/FormLabel.vue
<script lang="ts" setup>
import { Label } from "@/components/ui/label"
import { cn } from "@/lib/utils"
import type { LabelProps } from "radix-vue"
import type { HTMLAttributes } from "vue"
import { useFormField } from "./useFormField"

const props = defineProps<LabelProps & { class?: HTMLAttributes["class"] }>()

const { error, formItemId } = useFormField()
</script>

<template>
	<Label :class="cn(error && 'text-destructive', props.class)" :for="formItemId">
		<slot />
	</Label>
</template>
