// packages/vue/src/components/ui/dialog/DialogDescription.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DialogDescription, useForwardProps, type DialogDescriptionProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<DialogDescriptionProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<DialogDescription
		v-bind="forwardedProps"
		:class="cn('text-muted-foreground text-sm', props.class)"
	>
		<slot />
	</DialogDescription>
</template>

// packages/svelte/src/lib/components/ui/dialog/dialog-description.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Dialog as DialogPrimitive } from "bits-ui"

	type $$Props = DialogPrimitive.DescriptionProps

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<DialogPrimitive.Description
	class={cn("text-muted-foreground text-sm", className)}
	{...$$restProps}
>
	<slot />
</DialogPrimitive.Description>
