// packages/vue/src/components/ui/calendar/CalendarGrid.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { CalendarGrid, useForwardProps, type CalendarGridProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<CalendarGridProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<CalendarGrid
		:class="cn('w-full border-collapse space-y-1', props.class)"
		v-bind="forwardedProps"
	>
		<slot />
	</CalendarGrid>
</template>

// packages/svelte/src/lib/components/ui/calendar/calendar-grid.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Calendar as CalendarPrimitive } from "bits-ui"

	type $$Props = CalendarPrimitive.GridProps

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<CalendarPrimitive.Grid class={cn("w-full border-collapse space-y-1", className)} {...$$restProps}>
	<slot />
</CalendarPrimitive.Grid>
