// packages/vue/src/components/ui/calendar/CalendarPrevButton.vue
<script lang="ts" setup>
import { buttonVariants } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { ChevronLeftIcon } from "@radix-icons/vue"
import { CalendarPrev, useForwardProps, type CalendarPrevProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<CalendarPrevProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<CalendarPrev
		:class="
			cn(
				buttonVariants({ variant: 'outline' }),
				'h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100',
				props.class
			)
		"
		v-bind="forwardedProps"
	>
		<slot>
			<ChevronLeftIcon class="h-4 w-4" />
		</slot>
	</CalendarPrev>
</template>

// packages/svelte/src/lib/components/ui/calendar/calendar-prev-button.svelte
<script lang="ts">
	import { buttonVariants } from "$lib/components/ui/button/index.js"
	import { cn } from "$lib/utils.js"
	import { Calendar as CalendarPrimitive } from "bits-ui"
	import ChevronLeft from "svelte-radix/ChevronLeft.svelte"

	type $$Props = CalendarPrimitive.PrevButtonProps
	type $$Events = CalendarPrimitive.PrevButtonEvents

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<CalendarPrimitive.PrevButton
	on:click
	class={cn(
		buttonVariants({ variant: "outline" }),
		"h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100",
		className
	)}
	{...$$restProps}
	let:builder
>
	<slot {builder}>
		<ChevronLeft class="h-4 w-4" />
	</slot>
</CalendarPrimitive.PrevButton>
