// packages/vue/src/components/ui/calendar/CalendarHeader.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { CalendarHeader, useForwardProps, type CalendarHeaderProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<CalendarHeaderProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<CalendarHeader
		:class="cn('relative flex w-full items-center justify-between pt-1', props.class)"
		v-bind="forwardedProps"
	>
		<slot />
	</CalendarHeader>
</template>

// packages/svelte/src/lib/components/ui/calendar/calendar-header.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Calendar as CalendarPrimitive } from "bits-ui"

	type $$Props = CalendarPrimitive.HeaderProps

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<CalendarPrimitive.Header
	class={cn("relative flex w-full items-center justify-between pt-1", className)}
	{...$$restProps}
>
	<slot />
</CalendarPrimitive.Header>
