// packages/react/src/components/cmd/demo.tsx
import {
  CalendarIcon,
  EnvelopeClosedIcon,
  FaceIcon,
  GearIcon,
  InstagramLogoIcon,
  LinkedInLogoIcon,
  PersonIcon,
  RocketIcon,
  TwitterLogoIcon
} from "@radix-ui/react-icons"

import {
  CommandFooter,
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
  CommandShortcut,
  VertifcalSeparator,
  ActionPanel
} from "."
import { Button } from "../ui/button"
import React from "react"
import { cn } from "@/lib/utils"

export function CommandDemo({ className }: { className?: string }) {
  const [value, setValue] = React.useState("linear")
  const inputRef = React.useRef<HTMLInputElement | null>(null)
  const listRef = React.useRef(null)

  React.useEffect(() => {
    inputRef?.current?.focus()
  }, [])
  return (
    <Command
      className={cn("rounded-lg border shadow-md", className)}
      value={value}
      onValueChange={(v) => {
        console.log(v)
        setValue(v)
      }}
    >
      <CommandInput placeholder="Type a command or search..." />
      <CommandList className="h-full">
        <CommandEmpty>No results found.</CommandEmpty>
        <CommandGroup heading="Suggestions">
          <CommandItem>
            <TwitterLogoIcon className="mr-2 h-4 w-4" />
            <span>Twitter</span>
          </CommandItem>
          <CommandItem>
            <InstagramLogoIcon className="mr-2 h-4 w-4" />
            <span>Instagram</span>
          </CommandItem>
          <CommandItem>
            <LinkedInLogoIcon className="mr-2 h-4 w-4" />
            <span>LinkedIn</span>
          </CommandItem>
          <CommandItem>
            <CalendarIcon className="mr-2 h-4 w-4" />
            <span>Calendar</span>
          </CommandItem>
          <CommandItem>
            <FaceIcon className="mr-2 h-4 w-4" />
            <span>Search Emoji</span>
          </CommandItem>
          <CommandItem>
            <RocketIcon className="mr-2 h-4 w-4" />
            <span>Launch</span>
          </CommandItem>
        </CommandGroup>
        <CommandSeparator />
        <CommandGroup heading="Settings">
          <CommandItem>
            <PersonIcon className="mr-2 h-4 w-4" />
            <span>Profile</span>
            <CommandShortcut>⌘P</CommandShortcut>
          </CommandItem>
          <CommandItem>
            <EnvelopeClosedIcon className="mr-2 h-4 w-4" />
            <span>Mail</span>
            <CommandShortcut>⌘B</CommandShortcut>
          </CommandItem>
          <CommandItem>
            <GearIcon className="mr-2 h-4 w-4" />
            <span>Settings</span>
            <CommandShortcut>⌘S</CommandShortcut>
          </CommandItem>
        </CommandGroup>
      </CommandList>
      <CommandFooter>
        <GearIcon className="w-4 h-4 ml-2" />
        <div className="flex space-x-2 items-center">
          <Button variant="ghost" size="sm">
            Open Application
            <kbd className="ml-1">↵</kbd>
          </Button>
          <VertifcalSeparator />
          <ActionPanel
            listRef={listRef}
            selectedValue={value}
            inputRef={inputRef}
            actionItems={[
              { label: "Open Application", value: "open" },
              { label: "Show in Finder", value: "finder" },
              { label: "Show Info in Finder", value: "info" },
              { label: "Add to Favorites", value: "favorites" }
            ]}
          ></ActionPanel>
        </div>
      </CommandFooter>
    </Command>
  )
}

// packages/svelte5/src/lib/components/cmdk/demo.svelte
<script lang="ts">
	import { ModeDropdown, ModeToggle } from "$lib/components/theme"
	import { Button } from "$lib/components/ui/button"
	import * as Command from "$lib/components/ui/command"
	import { Separator } from "$lib/components/ui/separator/index.js"
	import { cn } from "$lib/utils"
	import { SettingsIcon } from "lucide-svelte"
	import Calculator from "lucide-svelte/icons/calculator"
	import Calendar from "lucide-svelte/icons/calendar"
	import CreditCard from "lucide-svelte/icons/credit-card"
	import Settings from "lucide-svelte/icons/settings"
	import Smile from "lucide-svelte/icons/smile"
	import User from "lucide-svelte/icons/user"
	import CmdkFooter from "./footer.svelte"

	let highlighted = ""
	$: {
		console.log("highlighted:", highlighted)
	}

	let searchTerm = ""
	$: {
		console.log("search term:", searchTerm)
	}
</script>

<Command.Root class={cn("rounded-lg border shadow-md", $$props.class)} bind:value={highlighted}>
	<Command.Input placeholder="Type a command or search..." autofocus bind:value={searchTerm} />
	<div class="grow">
		<Command.List>
			<Command.Empty>No results found.</Command.Empty>
			<Command.Group heading="Suggestions">
				<Command.Item onSelect={(v) => console.log("selected:", v)}>
					<Calendar class="mr-2 h-4 w-4" />
					<span>Calendar</span>
				</Command.Item>
				<Command.Item onSelect={(v) => console.log("selected:", v)}>
					<Smile class="mr-2 h-4 w-4" />
					<span>Search Emoji</span>
				</Command.Item>
				<Command.Item onSelect={(v) => console.log("selected:", v)}>
					<Calculator class="mr-2 h-4 w-4" />
					<span>Calculator</span>
				</Command.Item>
			</Command.Group>
			<Command.Separator />
			<Command.Group heading="Settings">
				<Command.Item onSelect={(v) => console.log("selected:", v)}>
					<User class="mr-2 h-4 w-4" />
					<span>Profile</span>
					<Command.Shortcut>⌘P</Command.Shortcut>
				</Command.Item>
				<Command.Item value="billllling">
					<CreditCard class="mr-2 h-4 w-4" />
					<span>Billing</span>
					<Command.Shortcut>⌘B</Command.Shortcut>
				</Command.Item>
				<Command.Item onSelect={(v) => console.log("selected:", v)}>
					<Settings class="mr-2 h-4 w-4" />
					<span>Settings</span>
					<Command.Shortcut>⌘S</Command.Shortcut>
				</Command.Item>
			</Command.Group>
		</Command.List>
	</div>
	<CmdkFooter class="">
		<SettingsIcon class="ml-2 h-4 w-4" />
		<div class="flex items-center space-x-2">
			<Button variant="ghost" size="sm">
				Open Application
				<kbd class="ml-1">↵</kbd>
			</Button>
			<Separator orientation="vertical" />
			<!-- <ActionPanel
        selectedValue={value}
        inputRef={actionInputRef}
        actionItems={[
          { label: "Open Application", value: "open" },
          { label: "Show in Finder", value: "finder" },
          { label: "Show Info in Finder", value: "info" },
          { label: "Add to Favorites", value: "favorites" },
        ]}
      ></ActionPanel> -->
		</div>
	</CmdkFooter>
</Command.Root>
