// packages/vue/src/components/ui/menubar/MenubarCheckboxItem.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { CheckIcon } from "@radix-icons/vue"
import {
	MenubarCheckboxItem,
	MenubarItemIndicator,
	useForwardPropsEmits,
	type MenubarCheckboxItemEmits,
	type MenubarCheckboxItemProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<MenubarCheckboxItemProps & { class?: HTMLAttributes["class"] }>()
const emits = defineEmits<MenubarCheckboxItemEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<MenubarCheckboxItem
		v-bind="forwarded"
		:class="
			cn(
				'focus:bg-accent focus:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
				props.class
			)
		"
	>
		<span class="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
			<MenubarItemIndicator>
				<CheckIcon class="h-4 w-4" />
			</MenubarItemIndicator>
		</span>
		<slot />
	</MenubarCheckboxItem>
</template>

// packages/svelte5/src/lib/components/ui/menubar/menubar-checkbox-item.svelte
<script lang="ts">
	import { Menubar as MenubarPrimitive, type WithoutChild } from "bits-ui";
	import Check from "svelte-radix/Check.svelte";
	import Minus from "svelte-radix/Minus.svelte";
	import { cn } from "@kksh/svelte5/utils.ts";

	let {
		ref = $bindable(null),
		checked = $bindable(false),
		class: className,
		children: childrenProp,
		...restProps
	}: WithoutChild<MenubarPrimitive.CheckboxItemProps> = $props();
</script>

<MenubarPrimitive.CheckboxItem
	bind:ref
	bind:checked
	class={cn(
		"data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
		className
	)}
	{...restProps}
>
	{#snippet children({ checked })}
		<span class="absolute left-2 flex size-3.5 items-center justify-center">
			{#if checked === "indeterminate"}
				<Minus class="size-4" />
			{:else}
				<Check class={cn("size-4", !checked && "text-transparent")} />
			{/if}
		</span>
		{@render childrenProp?.({ checked })}
	{/snippet}
</MenubarPrimitive.CheckboxItem>
