// packages/svelte/src/lib/components/ui/table/table-row.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLAttributes } from "svelte/elements"

	type $$Props = HTMLAttributes<HTMLTableRowElement> & {
		"data-state"?: unknown
	}

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<tr
	class={cn(
		"hover:bg-muted/50 data-[state=selected]:bg-muted border-b transition-colors",
		className
	)}
	{...$$restProps}
	on:click
	on:keydown
>
	<slot />
</tr>

// packages/vue/src/components/ui/table/TableRow.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<tr
		:class="
			cn('hover:bg-muted/50 data-[state=selected]:bg-muted border-b transition-colors', props.class)
		"
	>
		<slot />
	</tr>
</template>
