// packages/svelte/src/lib/components/ui/table/table-cell.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLTdAttributes } from "svelte/elements"

	type $$Props = HTMLTdAttributes

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<td
	class={cn(
		"p-2 align-middle [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
		className
	)}
	{...$$restProps}
	on:click
	on:keydown
>
	<slot />
</td>

// packages/vue/src/components/ui/table/TableCell.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<td
		:class="
			cn(
				'p-2 align-middle [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-0.5',
				props.class
			)
		"
	>
		<slot />
	</td>
</template>
