// packages/svelte5/src/lib/components/ui/select/select-scroll-up-button.svelte
<script lang="ts">
	import ChevronUp from "svelte-radix/ChevronUp.svelte";
	import { Select as SelectPrimitive, type WithoutChildrenOrChild } from "bits-ui";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: WithoutChildrenOrChild<SelectPrimitive.ScrollDownButtonProps> = $props();
</script>

<SelectPrimitive.ScrollUpButton
	bind:ref
	class={cn("flex cursor-default items-center justify-center py-1", className)}
	{...restProps}
>
	<ChevronUp class="size-4" />
</SelectPrimitive.ScrollUpButton>

// packages/vue/src/components/ui/select/SelectScrollUpButton.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { ChevronUpIcon } from "@radix-icons/vue"
import { SelectScrollUpButton, useForwardProps, type SelectScrollUpButtonProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<SelectScrollUpButtonProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<SelectScrollUpButton
		v-bind="forwardedProps"
		:class="cn('flex cursor-default items-center justify-center py-1', props.class)"
	>
		<slot>
			<ChevronUpIcon />
		</slot>
	</SelectScrollUpButton>
</template>
