// packages/svelte5/src/lib/components/ui/select/select-scroll-down-button.svelte
<script lang="ts">
	import ChevronDown from "svelte-radix/ChevronDown.svelte";
	import { Select as SelectPrimitive, type WithoutChildrenOrChild } from "bits-ui";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: WithoutChildrenOrChild<SelectPrimitive.ScrollDownButtonProps> = $props();
</script>

<SelectPrimitive.ScrollDownButton
	bind:ref
	class={cn("flex cursor-default items-center justify-center py-1", className)}
	{...restProps}
>
	<ChevronDown class="size-4" />
</SelectPrimitive.ScrollDownButton>

// packages/vue/src/components/ui/select/SelectScrollDownButton.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { ChevronDownIcon } from "@radix-icons/vue"
import {
	SelectScrollDownButton,
	useForwardProps,
	type SelectScrollDownButtonProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<SelectScrollDownButtonProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<SelectScrollDownButton
		v-bind="forwardedProps"
		:class="cn('flex cursor-default items-center justify-center py-1', props.class)"
	>
		<slot>
			<ChevronDownIcon />
		</slot>
	</SelectScrollDownButton>
</template>
