// packages/svelte/src/lib/components/ui/dropdown-menu/dropdown-menu-label.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui"

	type $$Props = DropdownMenuPrimitive.LabelProps & {
		inset?: boolean
	}

	let className: $$Props["class"] = undefined
	export let inset: $$Props["inset"] = undefined
	export { className as class }
</script>

<DropdownMenuPrimitive.Label
	class={cn("px-2 py-1.5 text-sm font-semibold", inset && "pl-8", className)}
	{...$$restProps}
>
	<slot />
</DropdownMenuPrimitive.Label>

// packages/vue/src/components/ui/dropdown-menu/DropdownMenuLabel.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DropdownMenuLabel, useForwardProps, type DropdownMenuLabelProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<
	DropdownMenuLabelProps & { class?: HTMLAttributes["class"]; inset?: boolean }
>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<DropdownMenuLabel
		v-bind="forwardedProps"
		:class="cn('px-2 py-1.5 text-sm font-semibold', inset && 'pl-8', props.class)"
	>
		<slot />
	</DropdownMenuLabel>
</template>
