// packages/svelte/src/lib/components/ui/dropdown-menu/dropdown-menu-shortcut.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLAttributes } from "svelte/elements"

	type $$Props = HTMLAttributes<HTMLSpanElement>

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<span class={cn("ml-auto text-xs tracking-widest opacity-60", className)} {...$$restProps}>
	<slot />
</span>

// packages/vue/src/components/ui/dropdown-menu/DropdownMenuShortcut.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<span :class="cn('ml-auto text-xs tracking-widest opacity-60', props.class)">
		<slot />
	</span>
</template>
