// packages/svelte5/src/lib/components/theme/theme-customizer.svelte
<script lang="ts">
	import { Button } from "$lib/components/ui/button/index.js"
	import { Label } from "$lib/components/ui/label/index.js"
	import { themes } from "$lib/registry/themes.js"
	import { cn } from "$lib/utils.js"
	// import { mode, setMode } from "mode-watcher"
	import { onMount } from "svelte"
	import Check from "svelte-radix/Check.svelte"
	import Moon from "svelte-radix/Moon.svelte"
	import Reset from "svelte-radix/Reset.svelte"
	import Sun from "svelte-radix/Sun.svelte"
	import { toast } from "svelte-sonner"
	import ThemeWrapper from "./theme-wrapper.svelte"
	import type { ThemeConfig } from "./types.js"

	export let config: ThemeConfig

	onMount(() => {
		toast.success("Hello world!")
	})

	$: mode = config.lightMode !== "auto" ? config.lightMode : undefined
</script>

<ThemeWrapper defaultTheme="zinc" class="flex flex-col space-y-4 md:space-y-6">
	<div class="flex items-start">
		<div class="space-y-1 pr-2">
			<div class="font-semibold leading-none tracking-tight">Customize</div>
			<div class="text-muted-foreground text-xs">Pick a style and color for your components.</div>
		</div>
		<Button
			variant="ghost"
			size="icon"
			class="ml-auto rounded-[0.5rem]"
			onclick={() => {
				config.radius = 0.5
				config.theme = "zinc"
			}}
		>
			<Reset />
			<span class="sr-only"> Reset </span>
		</Button>
	</div>
	<div class="flex flex-1 flex-col space-y-4 md:space-y-6">
		<div class="5 space-y-1">
			<Label class="text-xs">Color</Label>
			<div class="grid grid-cols-3 gap-2">
				{#each themes as theme (theme.name)}
					{@const isActive = config.theme === theme.name}
					<Button
						variant="outline"
						size="sm"
						onclick={() => {
							config.theme = theme.name
						}}
						class={cn("justify-start", isActive && "border-primary border-2")}
						style="--theme-primary: hsl({theme.activeColor[mode ?? 'dark']})"
					>
						<span
							class="mr-1 flex h-5 w-5 shrink-0 -translate-x-1 items-center justify-center rounded-full bg-[--theme-primary]"
						>
							{#if isActive}
								<Check class="h-4 w-4 text-white" />
							{/if}
						</span>
						{theme.label}
					</Button>
				{/each}
			</div>
		</div>
		<div class="space-y-1.5">
			<Label class="text-xs">Radius</Label>
			<div class="grid grid-cols-5 gap-2">
				{#each ["0", "0.3", "0.5", "0.75", "1.0"] as value, _ (value)}
					{@const valueFloat = Number.parseFloat(value)}
					<Button
						variant="outline"
						size="sm"
						onclick={() => {
							config.radius = valueFloat
						}}
						class={cn(config.radius === valueFloat && "border-primary border-2")}
					>
						{value}
					</Button>
				{/each}
			</div>
		</div>
		<div class="space-y-1.5">
			<Label class="text-xs">Mode</Label>
			<div class="grid grid-cols-3 gap-2">
				<Button
					variant="outline"
					size="sm"
					onclick={() => (config.lightMode = "light")}
					class={cn(config.lightMode === "light" && "border-primary border-2")}
				>
					<Sun class="mr-1 -translate-x-1" />
					Light
				</Button>
				<Button
					variant="outline"
					size="sm"
					onclick={() => (config.lightMode = "dark")}
					class={cn(config.lightMode === "dark" && "border-primary border-2")}
				>
					<Moon class="mr-1 -translate-x-1" />
					Dark
				</Button>
			</div>
		</div>
	</div>
</ThemeWrapper>

// packages/vue/src/components/theme/ThemeCustomizer.vue
<script lang="ts" setup>
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { colors } from "@/lib/themes/colors"
import { allColors, Theme } from "@/lib/themes/themes"
import { CheckIcon, MoonIcon, SunIcon } from "@radix-icons/vue"

const RADII = [0, 0.25, 0.5, 0.75, 1]
const lightMode = defineModel<"auto" | "light" | "dark">("lightMode")
const theme = defineModel<Theme["name"]>("theme")
const radius = defineModel<number>("radius")

function changeLightMode(mode: "light" | "dark" | "auto") {
	lightMode.value = mode
}

function setThemeColor(color: Theme["name"]) {
	theme.value = color
}

function setRadius(r: number) {
	radius.value = r
}
</script>

<template>
	<div class="p-2">
		<div class="space-y-1.5 pt-6">
			<Label for="color" class="text-xs"> Color </Label>
			<div class="grid grid-cols-3 gap-2 py-1.5">
				<Button
					v-for="(color, index) in allColors"
					:key="index"
					variant="outline"
					class="h-8 justify-start px-3"
					:class="color === theme ? 'border-foreground border-2' : ''"
					@click="setThemeColor(color)"
				>
					<span
						class="flex h-5 w-5 items-center justify-center rounded-full"
						:style="{ backgroundColor: colors[color][7].rgb }"
					>
						<CheckIcon v-if="color === theme" class="h-3 w-3 text-white" />
					</span>
					<span class="ml-2 text-xs capitalize">
						{{ color }}
					</span>
				</Button>
			</div>
		</div>
		<div class="space-y-1.5 pt-6">
			<Label for="radius" class="text-xs"> Radius </Label>
			<div class="grid grid-cols-5 gap-2 py-1.5">
				<Button
					v-for="(r, index) in RADII"
					:key="index"
					variant="outline"
					class="h-8 justify-center px-3"
					:class="r === radius ? 'border-foreground border-2' : ''"
					@click="setRadius(r)"
				>
					<span class="text-xs">
						{{ r }}
					</span>
				</Button>
			</div>
		</div>
		<div class="space-y-1.5 pt-6">
			<Label for="theme" class="text-xs"> Theme </Label>

			<div class="flex space-x-2 py-1.5">
				<Button
					class="h-8"
					variant="outline"
					:class="{ 'border-foreground border-2': lightMode == 'light' }"
					@click="changeLightMode('light')"
				>
					<SunIcon class="mr-2 h-4 w-4" />
					<span class="text-xs">Light</span>
				</Button>
				<Button
					class="h-8"
					variant="outline"
					:class="{ 'border-foreground border-2': lightMode == 'dark' }"
					@click="changeLightMode('dark')"
				>
					<MoonIcon class="mr-2 h-4 w-4" />
					<span class="text-xs">Dark</span>
				</Button>
				<Button
					class="h-8"
					variant="outline"
					:class="{ 'border-foreground border-2': lightMode == 'auto' }"
					@click="changeLightMode('auto')"
				>
					<MoonIcon class="mr-2 h-4 w-4" />
					<span class="text-xs">System</span>
				</Button>
			</div>
		</div>
	</div>
</template>
