// packages/vue/src/components/ui/table/Table.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<div class="relative w-full overflow-auto">
		<table :class="cn('w-full caption-bottom text-sm', props.class)">
			<slot />
		</table>
	</div>
</template>

// packages/svelte/src/lib/components/ui/table/table.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLTableAttributes } from "svelte/elements"

	type $$Props = HTMLTableAttributes

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<div class="relative w-full overflow-auto">
	<table class={cn("w-full caption-bottom text-sm", className)} {...$$restProps}>
		<slot />
	</table>
</div>
