// packages/vue/src/components/ui/table/TableFooter.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<tfoot :class="cn('bg-muted/50 border-t font-medium [&>tr]:last:border-b-0', props.class)">
		<slot />
	</tfoot>
</template>

// packages/svelte/src/lib/components/ui/table/table-footer.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLAttributes } from "svelte/elements"

	type $$Props = HTMLAttributes<HTMLTableSectionElement>

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<tfoot class={cn("bg-primary text-primary-foreground font-medium", className)} {...$$restProps}>
	<slot />
</tfoot>
