// packages/vue/src/components/ui/table/TableHead.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<th
		:class="
			cn(
				'text-muted-foreground h-10 px-2 text-left align-middle font-medium [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-0.5',
				props.class
			)
		"
	>
		<slot />
	</th>
</template>

// packages/svelte/src/lib/components/ui/table/table-head.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLThAttributes } from "svelte/elements"

	type $$Props = HTMLThAttributes

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<th
	class={cn(
		"text-muted-foreground h-10 px-2 text-left align-middle font-medium [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
		className
	)}
	{...$$restProps}
>
	<slot />
</th>
