// packages/react/src/components/theme/theme-wrapper.tsx
import React from "react"
import { useConfig } from "@/hooks/use-config"
import { cn } from "@/lib/utils"

interface ThemeWrapperProps extends React.ComponentProps<"div"> {
  defaultTheme?: string
}

export function ThemeWrapper({
  defaultTheme,
  children,
  className
}: ThemeWrapperProps) {
  const [config] = useConfig()

  return (
    <div
      className={cn(
        `theme-${defaultTheme || config.theme}`,
        "w-full",
        className
      )}
      style={
        {
          "--radius": `${defaultTheme ? 0.5 : config.radius}rem`
        } as React.CSSProperties
      }
    >
      {children}
    </div>
  )
}

// packages/svelte/src/lib/components/theme/theme-wrapper.svelte
<script lang="ts">
	import { config } from "$lib/stores/config"
	import { cn } from "$lib/utils.js"

	export let defaultTheme: string | undefined = undefined
	let className: string | undefined | null = undefined
	export { className as class }
</script>

<div
	class={cn(`theme-${defaultTheme || $config.theme}`, "w-full", className)}
	data-style={$config.style}
	style="--radius: {defaultTheme ? 0.5 : $config.radius}rem"
>
	<slot />
</div>
