// packages/vue/src/components/ui/breadcrumb/BreadcrumbEllipsis.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { DotsHorizontalIcon } from "@radix-icons/vue"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<span
		role="presentation"
		aria-hidden="true"
		:class="cn('flex h-9 w-9 items-center justify-center', props.class)"
	>
		<slot>
			<DotsHorizontalIcon class="h-4 w-4" />
		</slot>
		<span class="sr-only">More</span>
	</span>
</template>

// packages/svelte5/src/lib/components/ui/breadcrumb/breadcrumb-ellipsis.svelte
<script lang="ts">
	import DotsHorizontal from "svelte-radix/DotsHorizontal.svelte";
	import type { WithElementRef, WithoutChildren } from "bits-ui";
	import type { HTMLAttributes } from "svelte/elements";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: WithoutChildren<WithElementRef<HTMLAttributes<HTMLSpanElement>>> = $props();
</script>

<span
	bind:this={ref}
	role="presentation"
	aria-hidden="true"
	class={cn("flex size-9 items-center justify-center", className)}
	{...restProps}
>
	<DotsHorizontal class="size-4 outline-none" tabindex={-1} />
	<span class="sr-only">More</span>
</span>
