// packages/svelte/src/lib/components/ui/card/card.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLAttributes } from "svelte/elements"

	type $$Props = HTMLAttributes<HTMLDivElement>

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<!-- svelte-ignore a11y-no-static-element-interactions -->
<div
	class={cn("bg-card text-card-foreground rounded-xl border shadow", className)}
	{...$$restProps}
	on:click
	on:focusin
	on:focusout
	on:mouseenter
	on:mouseleave
>
	<slot />
</div>

// packages/vue/src/components/ui/card/Card.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<div :class="cn('bg-card text-card-foreground rounded-xl border shadow', props.class)">
		<slot />
	</div>
</template>
