// packages/svelte5/src/lib/components/theme/theme-wrapper.svelte
<script lang="ts">
	import { config } from "$lib/stores/config.js";
	import { type PrimitiveDivAttributes, cn, updateTheme } from "$lib/utils.js";
	import { setMode } from "mode-watcher"

	let {
		class: className,
		defaultTheme,
		children,
	}: PrimitiveDivAttributes & { defaultTheme?: string } = $props();

	config.subscribe((val) => {
		setMode(val.lightMode)
	})
</script>

<div
	class={cn(`theme-${defaultTheme || $config.theme}`, "w-full", className)}
	data-style="nova"
	style="--radius: {defaultTheme ? 0.5 : $config.radius}rem"
>
	{@render children?.()}
</div>

// packages/react/src/components/theme/theme-wrapper.tsx
import React from "react"
import { useConfig } from "@/hooks/use-config"
import { cn } from "@/lib/utils"

interface ThemeWrapperProps extends React.ComponentProps<"div"> {
  defaultTheme?: string
}

export function ThemeWrapper({
  defaultTheme,
  children,
  className
}: ThemeWrapperProps) {
  const [config] = useConfig()

  return (
    <div
      className={cn(
        `theme-${defaultTheme || config.theme}`,
        "w-full",
        className
      )}
      style={
        {
          "--radius": `${defaultTheme ? 0.5 : config.radius}rem`
        } as React.CSSProperties
      }
    >
      {children}
    </div>
  )
}
