// packages/svelte/src/lib/components/ui/menubar/menubar-radio-item.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Menubar as MenubarPrimitive } from "bits-ui"
	import DotFilled from "svelte-radix/DotFilled.svelte"

	type $$Props = MenubarPrimitive.RadioItemProps
	type $$Events = MenubarPrimitive.RadioItemEvents
	let className: $$Props["class"] = undefined
	export let value: $$Props["value"]
	export { className as class }
</script>

<MenubarPrimitive.RadioItem
	{value}
	class={cn(
		"data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
		className
	)}
	{...$$restProps}
	on:click
	on:keydown
	on:focusin
	on:focusout
	on:pointerleave
	on:pointermove
	on:pointerdown
>
	<span class="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
		<MenubarPrimitive.RadioIndicator>
			<DotFilled class="h-4 w-4 fill-current" />
		</MenubarPrimitive.RadioIndicator>
	</span>
	<slot />
</MenubarPrimitive.RadioItem>

// packages/vue/src/components/ui/menubar/MenubarRadioItem.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DotFilledIcon } from "@radix-icons/vue"
import {
	MenubarItemIndicator,
	MenubarRadioItem,
	useForwardPropsEmits,
	type MenubarRadioItemEmits,
	type MenubarRadioItemProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<MenubarRadioItemProps & { class?: HTMLAttributes["class"] }>()
const emits = defineEmits<MenubarRadioItemEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<MenubarRadioItem
		v-bind="forwarded"
		:class="
			cn(
				'focus:bg-accent focus:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
				props.class
			)
		"
	>
		<span class="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
			<MenubarItemIndicator>
				<DotFilledIcon class="h-4 w-4 fill-current" />
			</MenubarItemIndicator>
		</span>
		<slot />
	</MenubarRadioItem>
</template>
