// packages/svelte/src/lib/components/ui/menubar/menubar-shortcut.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLAttributes } from "svelte/elements"

	type $$Props = HTMLAttributes<HTMLSpanElement>
	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<span
	class={cn("text-muted-foreground ml-auto text-xs tracking-widest", className)}
	{...$$restProps}
>
	<slot />
</span>

// packages/vue/src/components/ui/menubar/MenubarShortcut.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<span :class="cn('text-muted-foreground ml-auto text-xs tracking-widest', props.class)">
		<slot />
	</span>
</template>
