// packages/svelte/src/lib/components/ui/menubar/menubar-content.svelte
<script lang="ts">
	import { cn, flyAndScale } from "$lib/utils.js"
	import { Menubar as MenubarPrimitive } from "bits-ui"

	type $$Props = MenubarPrimitive.ContentProps
	let className: $$Props["class"] = undefined
	export let align: $$Props["align"] = "start"
	export let alignOffset: $$Props["alignOffset"] = -4
	export let sideOffset: $$Props["sideOffset"] = 8
	export let transition: $$Props["transition"] = flyAndScale
	export let transitionConfig: $$Props["transitionConfig"] = undefined
	export { className as class }
</script>

<MenubarPrimitive.Content
	{transition}
	{transitionConfig}
	{sideOffset}
	{align}
	{alignOffset}
	class={cn(
		"bg-popover text-popover-foreground z-50 min-w-[12rem] rounded-md border p-1 shadow-md focus:outline-none",
		className
	)}
	{...$$restProps}
>
	<slot />
</MenubarPrimitive.Content>

// packages/vue/src/components/ui/menubar/MenubarContent.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { MenubarContent, MenubarPortal, useForwardProps, type MenubarContentProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = withDefaults(
	defineProps<MenubarContentProps & { class?: HTMLAttributes["class"] }>(),
	{
		align: "start",
		alignOffset: -4,
		sideOffset: 8
	}
)

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<MenubarPortal>
		<MenubarContent
			v-bind="forwardedProps"
			:class="
				cn(
					'bg-popover text-popover-foreground data-[state=open]:animate-in data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 z-50 min-w-48 overflow-hidden rounded-md border p-1 shadow-md',
					props.class
				)
			"
		>
			<slot />
		</MenubarContent>
	</MenubarPortal>
</template>
