// packages/svelte/src/lib/components/ui/menubar/menubar-sub-trigger.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Menubar as MenubarPrimitive } from "bits-ui"
	import ChevronRight from "svelte-radix/ChevronRight.svelte"

	type $$Props = MenubarPrimitive.SubTriggerProps & {
		inset?: boolean
	}
	type $$Events = MenubarPrimitive.SubTriggerEvents

	let className: $$Props["class"] = undefined
	export let inset: $$Props["inset"] = undefined
	export { className as class }
</script>

<MenubarPrimitive.SubTrigger
	class={cn(
		"data-[highlighted]:bg-accent data-[state=open]:bg-accent data-[highlighted]:text-accent-foreground data-[state=open]:text-accent-foreground flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
		inset && "pl-8",
		className
	)}
	{...$$restProps}
	on:click
	on:keydown
	on:focusin
	on:focusout
	on:pointerleave
	on:pointermove
>
	<slot />
	<ChevronRight class="ml-auto h-4 w-4" />
</MenubarPrimitive.SubTrigger>

// packages/vue/src/components/ui/menubar/MenubarSubTrigger.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { ChevronRightIcon } from "@radix-icons/vue"
import { MenubarSubTrigger, useForwardProps, type MenubarSubTriggerProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<
	MenubarSubTriggerProps & { class?: HTMLAttributes["class"]; inset?: boolean }
>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<MenubarSubTrigger
		v-bind="forwardedProps"
		:class="
			cn(
				'focus:bg-accent focus:text-accent-foreground data-[state=open]:bg-accent data-[state=open]:text-accent-foreground flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none',
				inset && 'pl-8',
				props.class
			)
		"
	>
		<slot />
		<ChevronRightIcon class="ml-auto h-4 w-4" />
	</MenubarSubTrigger>
</template>
