// packages/svelte5/src/lib/components/ui/menubar/menubar.svelte
<script lang="ts">
	import { Menubar as MenubarPrimitive } from "bits-ui";
	import { cn } from "@kksh/svelte5/utils.ts";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: MenubarPrimitive.RootProps = $props();
</script>

<MenubarPrimitive.Root
	bind:ref
	class={cn(
		"bg-background flex h-9 items-center space-x-1 rounded-md border p-1 shadow-sm",
		className
	)}
	{...restProps}
/>

// packages/vue/src/components/ui/menubar/Menubar.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import {
	MenubarRoot,
	useForwardPropsEmits,
	type MenubarRootEmits,
	type MenubarRootProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<MenubarRootProps & { class?: HTMLAttributes["class"] }>()
const emits = defineEmits<MenubarRootEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<MenubarRoot
		v-bind="forwarded"
		:class="
			cn(
				'bg-background flex h-9 items-center space-x-1 rounded-md border p-1 shadow-sm',
				props.class
			)
		"
	>
		<slot />
	</MenubarRoot>
</template>
