// packages/vue/src/components/ui/tabs/TabsContent.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { TabsContent, type TabsContentProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<TabsContentProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<TabsContent
		:class="
			cn(
				'ring-offset-background focus-visible:ring-ring mt-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2',
				props.class
			)
		"
		v-bind="delegatedProps"
	>
		<slot />
	</TabsContent>
</template>

// packages/svelte/src/lib/components/ui/tabs/tabs-content.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Tabs as TabsPrimitive } from "bits-ui"

	type $$Props = TabsPrimitive.ContentProps

	let className: $$Props["class"] = undefined
	export let value: $$Props["value"]
	export { className as class }
</script>

<TabsPrimitive.Content
	class={cn(
		"ring-offset-background focus-visible:ring-ring mt-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2",
		className
	)}
	{value}
	{...$$restProps}
>
	<slot />
</TabsPrimitive.Content>
