// packages/vue/src/components/ui/tabs/TabsTrigger.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { TabsTrigger, useForwardProps, type TabsTriggerProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<TabsTriggerProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<TabsTrigger
		v-bind="forwardedProps"
		:class="
			cn(
				'ring-offset-background focus-visible:ring-ring data-[state=active]:bg-background data-[state=active]:text-foreground inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1 text-sm font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:shadow',
				props.class
			)
		"
	>
		<slot />
	</TabsTrigger>
</template>

// packages/svelte/src/lib/components/ui/tabs/tabs-trigger.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Tabs as TabsPrimitive } from "bits-ui"

	type $$Props = TabsPrimitive.TriggerProps
	type $$Events = TabsPrimitive.TriggerEvents

	let className: $$Props["class"] = undefined
	export let value: $$Props["value"]
	export { className as class }
</script>

<TabsPrimitive.Trigger
	class={cn(
		"ring-offset-background focus-visible:ring-ring data-[state=active]:bg-background data-[state=active]:text-foreground inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1 text-sm font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:shadow",
		className
	)}
	{value}
	{...$$restProps}
	on:click
	on:keydown
	on:focus
>
	<slot />
</TabsPrimitive.Trigger>
