// packages/vue/src/components/ui/context-menu/ContextMenuCheckboxItem.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { CheckIcon } from "@radix-icons/vue"
import {
	ContextMenuCheckboxItem,
	ContextMenuItemIndicator,
	useForwardPropsEmits,
	type ContextMenuCheckboxItemEmits,
	type ContextMenuCheckboxItemProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<ContextMenuCheckboxItemProps & { class?: HTMLAttributes["class"] }>()
const emits = defineEmits<ContextMenuCheckboxItemEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<ContextMenuCheckboxItem
		v-bind="forwarded"
		:class="
			cn(
				'focus:bg-accent focus:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
				props.class
			)
		"
	>
		<span class="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
			<ContextMenuItemIndicator>
				<CheckIcon class="h-4 w-4" />
			</ContextMenuItemIndicator>
		</span>
		<slot />
	</ContextMenuCheckboxItem>
</template>

// packages/svelte5/src/lib/components/ui/context-menu/context-menu-checkbox-item.svelte
<script lang="ts">
	import { ContextMenu as ContextMenuPrimitive, type WithoutChildrenOrChild } from "bits-ui";
	import Check from "svelte-radix/Check.svelte";
	import Minus from "svelte-radix/Minus.svelte";
	import type { Snippet } from "svelte";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		checked = $bindable(),
		children,
		...restProps
	}: WithoutChildrenOrChild<ContextMenuPrimitive.CheckboxItemProps> & {
		children?: Snippet;
	} = $props();
</script>

<ContextMenuPrimitive.CheckboxItem
	bind:checked
	bind:ref
	class={cn(
		"data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
		className
	)}
	{...restProps}
>
	<span class="absolute left-2 flex size-3.5 items-center justify-center">
		{#if checked === "indeterminate"}
			<Minus class="size-4" />
		{:else}
			<Check class={cn("size-4", !checked && "text-transparent")} />
		{/if}
	</span>
	{@render children?.()}
</ContextMenuPrimitive.CheckboxItem>
