// packages/svelte/src/lib/components/ui/alert-dialog/alert-dialog-content.svelte
<script lang="ts">
	import { cn, flyAndScale } from "$lib/utils.js"
	import { AlertDialog as AlertDialogPrimitive } from "bits-ui"
	import * as AlertDialog from "./index.js"

	type $$Props = AlertDialogPrimitive.ContentProps

	let className: $$Props["class"] = undefined
	export let transition: $$Props["transition"] = flyAndScale
	export let transitionConfig: $$Props["transitionConfig"] = undefined
	export { className as class }
</script>

<AlertDialog.Portal>
	<AlertDialog.Overlay />
	<AlertDialogPrimitive.Content
		{transition}
		{transitionConfig}
		class={cn(
			"bg-background fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border p-6 shadow-lg  sm:rounded-lg md:w-full",
			className
		)}
		{...$$restProps}
	>
		<slot />
	</AlertDialogPrimitive.Content>
</AlertDialog.Portal>

// packages/vue/src/components/ui/alert-dialog/AlertDialogContent.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import {
	AlertDialogContent,
	AlertDialogOverlay,
	AlertDialogPortal,
	useForwardPropsEmits,
	type AlertDialogContentEmits,
	type AlertDialogContentProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<AlertDialogContentProps & { class?: HTMLAttributes["class"] }>()
const emits = defineEmits<AlertDialogContentEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<AlertDialogPortal>
		<AlertDialogOverlay
			class="data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 fixed inset-0 z-50 bg-black/80"
		/>
		<AlertDialogContent
			v-bind="forwarded"
			:class="
				cn(
					'bg-background data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] fixed left-1/2 top-1/2 z-50 grid w-full max-w-lg -translate-x-1/2 -translate-y-1/2 gap-4 border p-6 shadow-lg duration-200 sm:rounded-lg',
					props.class
				)
			"
		>
			<slot />
		</AlertDialogContent>
	</AlertDialogPortal>
</template>
