// packages/svelte/src/lib/components/ui/alert-dialog/alert-dialog-title.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { AlertDialog as AlertDialogPrimitive } from "bits-ui"

	type $$Props = AlertDialogPrimitive.TitleProps

	let className: $$Props["class"] = undefined
	export let level: $$Props["level"] = "h3"
	export { className as class }
</script>

<AlertDialogPrimitive.Title class={cn("text-lg font-semibold", className)} {level} {...$$restProps}>
	<slot />
</AlertDialogPrimitive.Title>

// packages/vue/src/components/ui/alert-dialog/AlertDialogTitle.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { AlertDialogTitle, type AlertDialogTitleProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<AlertDialogTitleProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<AlertDialogTitle v-bind="delegatedProps" :class="cn('text-lg font-semibold', props.class)">
		<slot />
	</AlertDialogTitle>
</template>
