// packages/svelte/src/lib/components/ui/alert-dialog/alert-dialog-cancel.svelte
<script lang="ts">
	import { buttonVariants } from "$lib/components/ui/button/index.js"
	import { cn } from "$lib/utils.js"
	import { AlertDialog as AlertDialogPrimitive } from "bits-ui"

	type $$Props = AlertDialogPrimitive.CancelProps
	type $$Events = AlertDialogPrimitive.CancelEvents

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<AlertDialogPrimitive.Cancel
	class={cn(buttonVariants({ variant: "outline" }), "mt-2 sm:mt-0", className)}
	{...$$restProps}
	on:click
	on:keydown
	let:builder
>
	<slot {builder} />
</AlertDialogPrimitive.Cancel>

// packages/vue/src/components/ui/alert-dialog/AlertDialogCancel.vue
<script setup lang="ts">
import { buttonVariants } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { AlertDialogCancel, type AlertDialogCancelProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<AlertDialogCancelProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<AlertDialogCancel
		v-bind="delegatedProps"
		:class="cn(buttonVariants({ variant: 'outline' }), 'mt-2 sm:mt-0', props.class)"
	>
		<slot />
	</AlertDialogCancel>
</template>
