// packages/vue/src/components/ui/carousel/CarouselItem.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { WithClassAsProps } from "./interface"
import { useCarousel } from "./useCarousel"

const props = defineProps<WithClassAsProps>()

const { orientation } = useCarousel()
</script>

<template>
	<div
		role="group"
		aria-roledescription="slide"
		:class="
			cn(
				'min-w-0 shrink-0 grow-0 basis-full',
				orientation === 'horizontal' ? 'pl-4' : 'pt-4',
				props.class
			)
		"
	>
		<slot />
	</div>
</template>

// packages/svelte/src/lib/components/ui/carousel/carousel-item.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLAttributes } from "svelte/elements"
	import { getEmblaContext } from "./context.js"

	type $$Props = HTMLAttributes<HTMLDivElement>
	let className: string | undefined | null = undefined
	export { className as class }

	const { orientation } = getEmblaContext("<Carousel.Item/>")
</script>

<div
	role="group"
	aria-roledescription="slide"
	class={cn(
		"min-w-0 shrink-0 grow-0 basis-full",
		$orientation === "horizontal" ? "pl-4" : "pt-4",
		className
	)}
	data-embla-slide=""
	{...$$restProps}
>
	<slot />
</div>
