// packages/vue/src/components/ui/alert-dialog/AlertDialogCancel.vue
<script setup lang="ts">
import { buttonVariants } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { AlertDialogCancel, type AlertDialogCancelProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<AlertDialogCancelProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<AlertDialogCancel
		v-bind="delegatedProps"
		:class="cn(buttonVariants({ variant: 'outline' }), 'mt-2 sm:mt-0', props.class)"
	>
		<slot />
	</AlertDialogCancel>
</template>

// packages/svelte5/src/lib/components/ui/alert-dialog/alert-dialog-cancel.svelte
<script lang="ts">
	import { AlertDialog as AlertDialogPrimitive } from "bits-ui";
	import { buttonVariants } from "@kksh/svelte5/components/ui/button/index.js";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		class: className,
		ref = $bindable(null),
		...restProps
	}: AlertDialogPrimitive.CancelProps = $props();
</script>

<AlertDialogPrimitive.Cancel
	bind:ref
	class={cn(buttonVariants({ variant: "outline" }), "mt-2 sm:mt-0", className)}
	{...restProps}
/>
