// packages/vue/src/components/ui/drawer/DrawerTitle.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import type { DrawerTitleProps } from "vaul-vue"
import { DrawerTitle } from "vaul-vue"
import { computed, type HtmlHTMLAttributes } from "vue"

const props = defineProps<DrawerTitleProps & { class?: HtmlHTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<DrawerTitle
		v-bind="delegatedProps"
		:class="cn('text-lg font-semibold leading-none tracking-tight', props.class)"
	>
		<slot />
	</DrawerTitle>
</template>

// packages/svelte/src/lib/components/ui/drawer/drawer-title.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Drawer as DrawerPrimitive } from "vaul-svelte"

	type $$Props = DrawerPrimitive.TitleProps

	export let el: $$Props["el"] = undefined
	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<DrawerPrimitive.Title
	bind:el
	class={cn("text-lg font-semibold leading-none tracking-tight", className)}
	{...$$restProps}
>
	<slot />
</DrawerPrimitive.Title>
