// packages/svelte/src/lib/components/ui/badge/badge.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { badgeVariants, type Variant } from "./index.js"

	let className: string | undefined | null = undefined
	export let href: string | undefined = undefined
	export let variant: Variant = "default"
	export { className as class }
</script>

<svelte:element
	this={href ? "a" : "span"}
	{href}
	class={cn(badgeVariants({ variant, className }))}
	{...$$restProps}
>
	<slot />
</svelte:element>

// packages/vue/src/components/ui/badge/Badge.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"
import { badgeVariants, type BadgeVariants } from "."

const props = defineProps<{
	variant?: BadgeVariants["variant"]
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<div :class="cn(badgeVariants({ variant }), props.class)">
		<slot />
	</div>
</template>
