// packages/svelte/src/lib/components/ui/breadcrumb/breadcrumb-ellipsis.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import DotsHorizontal from "svelte-radix/DotsHorizontal.svelte"
	import type { HTMLAttributes } from "svelte/elements"

	type $$Props = HTMLAttributes<HTMLSpanElement> & {
		el?: HTMLSpanElement
	}

	export let el: $$Props["el"] = undefined
	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<span
	bind:this={el}
	role="presentation"
	aria-hidden="true"
	class={cn("flex h-9 w-9 items-center justify-center", className)}
	{...$$restProps}
>
	<DotsHorizontal class="h-4 w-4 outline-none" tabindex="-1" />
	<span class="sr-only">More</span>
</span>

// packages/vue/src/components/ui/breadcrumb/BreadcrumbEllipsis.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { DotsHorizontalIcon } from "@radix-icons/vue"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<span
		role="presentation"
		aria-hidden="true"
		:class="cn('flex h-9 w-9 items-center justify-center', props.class)"
	>
		<slot>
			<DotsHorizontalIcon class="h-4 w-4" />
		</slot>
		<span class="sr-only">More</span>
	</span>
</template>
