// packages/svelte5/src/lib/components/ui/breadcrumb/breadcrumb-separator.svelte
<script lang="ts">
	import ChevronRight from "svelte-radix/ChevronRight.svelte";
	import type { WithElementRef } from "bits-ui";
	import type { HTMLLiAttributes } from "svelte/elements";
	import { cn } from "@kksh/svelte5/utils.ts";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLLiAttributes> = $props();
</script>

<li
	role="presentation"
	aria-hidden="true"
	class={cn("[&>svg]:size-3.5", className)}
	bind:this={ref}
	{...restProps}
>
	{#if children}
		{@render children?.()}
	{:else}
		<ChevronRight />
	{/if}
</li>

// packages/vue/src/components/ui/breadcrumb/BreadcrumbSeparator.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { ChevronRightIcon } from "@radix-icons/vue"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<li role="presentation" aria-hidden="true" :class="cn('[&>svg]:size-3.5', props.class)">
		<slot>
			<ChevronRightIcon />
		</slot>
	</li>
</template>
