// packages/svelte/src/lib/components/ui/breadcrumb/breadcrumb-link.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLAnchorAttributes } from "svelte/elements"

	type $$Props = HTMLAnchorAttributes & {
		el?: HTMLAnchorElement
		asChild?: boolean
	}

	export let href: $$Props["href"] = undefined
	export let el: $$Props["el"] = undefined
	export let asChild: $$Props["asChild"] = false
	let className: $$Props["class"] = undefined
	export { className as class }

	let attrs: Record<string, unknown>

	$: attrs = {
		class: cn("hover:text-foreground transition-colors", className),
		href,
		...$$restProps
	}
</script>

{#if asChild}
	<slot {attrs} />
{:else}
	<a bind:this={el} {...attrs} {href}>
		<slot {attrs} />
	</a>
{/if}

// packages/vue/src/components/ui/breadcrumb/BreadcrumbLink.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { Primitive, type PrimitiveProps } from "radix-vue"
import type { HTMLAttributes } from "vue"

const props = withDefaults(defineProps<PrimitiveProps & { class?: HTMLAttributes["class"] }>(), {
	as: "a"
})
</script>

<template>
	<Primitive
		:as="as"
		:as-child="asChild"
		:class="cn('hover:text-foreground transition-colors', props.class)"
	>
		<slot />
	</Primitive>
</template>
