// packages/svelte/src/lib/components/ui/breadcrumb/breadcrumb-list.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLOlAttributes } from "svelte/elements"

	type $$Props = HTMLOlAttributes & {
		el?: HTMLOListElement
	}

	export let el: $$Props["el"] = undefined
	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<ol
	bind:this={el}
	class={cn(
		"text-muted-foreground flex flex-wrap items-center gap-1.5 break-words text-sm sm:gap-2.5",
		className
	)}
	{...$$restProps}
>
	<slot />
</ol>

// packages/vue/src/components/ui/breadcrumb/BreadcrumbList.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<ol
		:class="
			cn(
				'text-muted-foreground flex flex-wrap items-center gap-1.5 break-words text-sm sm:gap-2.5',
				props.class
			)
		"
	>
		<slot />
	</ol>
</template>
