// packages/svelte5/src/lib/components/ui/breadcrumb/breadcrumb-list.svelte
<script lang="ts">
	import type { WithElementRef } from "bits-ui";
	import type { HTMLOlAttributes } from "svelte/elements";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLOlAttributes> = $props();
</script>

<ol
	bind:this={ref}
	class={cn(
		"text-muted-foreground flex flex-wrap items-center gap-1.5 break-words text-sm sm:gap-2.5",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</ol>

// packages/vue/src/components/ui/breadcrumb/BreadcrumbList.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
	class?: HTMLAttributes["class"]
}>()
</script>

<template>
	<ol
		:class="
			cn(
				'text-muted-foreground flex flex-wrap items-center gap-1.5 break-words text-sm sm:gap-2.5',
				props.class
			)
		"
	>
		<slot />
	</ol>
</template>
