// packages/svelte5/src/lib/components/ui/drawer/drawer-header.svelte
<script lang="ts">
	import type { WithElementRef } from "bits-ui";
	import type { HTMLAttributes } from "svelte/elements";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	class={cn("grid gap-1.5 p-4 text-center sm:text-left", className)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/vue/src/components/ui/drawer/DrawerHeader.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import type { HtmlHTMLAttributes } from "vue"

const props = defineProps<{
	class?: HtmlHTMLAttributes["class"]
}>()
</script>

<template>
	<div :class="cn('grid gap-1.5 p-4 text-center sm:text-left', props.class)">
		<slot />
	</div>
</template>
