// packages/svelte/src/lib/components/ui/drawer/drawer-overlay.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Drawer as DrawerPrimitive } from "vaul-svelte"

	type $$Props = DrawerPrimitive.OverlayProps

	export let el: $$Props["el"] = undefined
	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<DrawerPrimitive.Overlay
	bind:el
	class={cn("fixed inset-0 z-50 bg-black/80", className)}
	{...$$restProps}
>
	<slot />
</DrawerPrimitive.Overlay>

// packages/vue/src/components/ui/drawer/DrawerOverlay.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import type { DialogOverlayProps } from "radix-vue"
import { DrawerOverlay } from "vaul-vue"
import { computed, type HtmlHTMLAttributes } from "vue"

const props = defineProps<DialogOverlayProps & { class?: HtmlHTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<DrawerOverlay
		v-bind="delegatedProps"
		:class="cn('fixed inset-0 z-50 bg-black/80', props.class)"
	/>
</template>
