// packages/svelte5/src/lib/components/ui/drawer/drawer-overlay.svelte
<script lang="ts">
	import { Drawer as DrawerPrimitive } from "vaul-svelte";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: DrawerPrimitive.OverlayProps = $props();
</script>

<DrawerPrimitive.Overlay
	bind:ref
	class={cn("fixed inset-0 z-50 bg-black/80", className)}
	{...restProps}
/>

// packages/vue/src/components/ui/drawer/DrawerOverlay.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import type { DialogOverlayProps } from "radix-vue"
import { DrawerOverlay } from "vaul-vue"
import { computed, type HtmlHTMLAttributes } from "vue"

const props = defineProps<DialogOverlayProps & { class?: HtmlHTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<DrawerOverlay
		v-bind="delegatedProps"
		:class="cn('fixed inset-0 z-50 bg-black/80', props.class)"
	/>
</template>
