// packages/svelte/src/lib/components/ui/drawer/drawer-description.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Drawer as DrawerPrimitive } from "vaul-svelte"

	type $$Props = DrawerPrimitive.DescriptionProps

	export let el: $$Props["el"] = undefined
	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<DrawerPrimitive.Description
	bind:el
	class={cn("text-muted-foreground text-sm", className)}
	{...$$restProps}
>
	<slot />
</DrawerPrimitive.Description>

// packages/vue/src/components/ui/drawer/DrawerDescription.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import type { DrawerDescriptionProps } from "vaul-vue"
import { DrawerDescription } from "vaul-vue"
import { computed, type HtmlHTMLAttributes } from "vue"

const props = defineProps<DrawerDescriptionProps & { class?: HtmlHTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<DrawerDescription
		v-bind="delegatedProps"
		:class="cn('text-muted-foreground text-sm', props.class)"
	>
		<slot />
	</DrawerDescription>
</template>
