// packages/svelte/src/lib/components/ui/drawer/drawer-header.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLAttributes } from "svelte/elements"

	type $$Props = HTMLAttributes<HTMLDivElement> & {
		el?: HTMLDivElement
	}
	export let el: $$Props["el"] = undefined
	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<div
	bind:this={el}
	class={cn("grid gap-1.5 p-4 text-center sm:text-left", className)}
	{...$$restProps}
>
	<slot />
</div>

// packages/vue/src/components/ui/drawer/DrawerHeader.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import type { HtmlHTMLAttributes } from "vue"

const props = defineProps<{
	class?: HtmlHTMLAttributes["class"]
}>()
</script>

<template>
	<div :class="cn('grid gap-1.5 p-4 text-center sm:text-left', props.class)">
		<slot />
	</div>
</template>
