// packages/svelte5/src/lib/components/ui/drawer/drawer-description.svelte
<script lang="ts">
	import { Drawer as DrawerPrimitive } from "vaul-svelte";
	import { cn } from "@kksh/svelte5/utils.ts";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: DrawerPrimitive.DescriptionProps = $props();
</script>

<DrawerPrimitive.Description
	bind:ref
	class={cn("text-muted-foreground text-sm", className)}
	{...restProps}
/>

// packages/vue/src/components/ui/drawer/DrawerDescription.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import type { DrawerDescriptionProps } from "vaul-vue"
import { DrawerDescription } from "vaul-vue"
import { computed, type HtmlHTMLAttributes } from "vue"

const props = defineProps<DrawerDescriptionProps & { class?: HtmlHTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<DrawerDescription
		v-bind="delegatedProps"
		:class="cn('text-muted-foreground text-sm', props.class)"
	>
		<slot />
	</DrawerDescription>
</template>
