// packages/svelte/src/lib/components/ui/drawer/drawer-content.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Drawer as DrawerPrimitive } from "vaul-svelte"
	import DrawerOverlay from "./drawer-overlay.svelte"

	type $$Props = DrawerPrimitive.ContentProps

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<DrawerPrimitive.Portal>
	<DrawerOverlay />
	<DrawerPrimitive.Content
		class={cn(
			"bg-background fixed inset-x-0 bottom-0 z-50 mt-24 flex h-auto flex-col rounded-t-[10px] border",
			className
		)}
		{...$$restProps}
	>
		<div class="bg-muted mx-auto mt-4 h-2 w-[100px] rounded-full"></div>
		<slot />
	</DrawerPrimitive.Content>
</DrawerPrimitive.Portal>

// packages/vue/src/components/ui/drawer/DrawerContent.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import type { DialogContentEmits, DialogContentProps } from "radix-vue"
import { useForwardPropsEmits } from "radix-vue"
import { DrawerContent, DrawerPortal } from "vaul-vue"
import type { HtmlHTMLAttributes } from "vue"
import DrawerOverlay from "./DrawerOverlay.vue"

const props = defineProps<DialogContentProps & { class?: HtmlHTMLAttributes["class"] }>()
const emits = defineEmits<DialogContentEmits>()

const forwarded = useForwardPropsEmits(props, emits)
</script>

<template>
	<DrawerPortal>
		<DrawerOverlay />
		<DrawerContent
			v-bind="forwarded"
			:class="
				cn(
					'bg-background fixed inset-x-0 bottom-0 z-50 mt-24 flex h-auto flex-col rounded-t-[10px] border',
					props.class
				)
			"
		>
			<div class="bg-muted mx-auto mt-4 h-2 w-[100px] rounded-full" />
			<slot />
		</DrawerContent>
	</DrawerPortal>
</template>
