// packages/vue/src/components/ui/select/SelectTrigger.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { CaretSortIcon } from "@radix-icons/vue"
import { SelectIcon, SelectTrigger, useForwardProps, type SelectTriggerProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<SelectTriggerProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<SelectTrigger
		v-bind="forwardedProps"
		:class="
			cn(
				'border-input ring-offset-background placeholder:text-muted-foreground focus:ring-ring flex h-9 w-full items-center justify-between whitespace-nowrap rounded-md border bg-transparent px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-1 disabled:cursor-not-allowed disabled:opacity-50 [&>span]:line-clamp-1',
				props.class
			)
		"
	>
		<slot />
		<SelectIcon as-child>
			<CaretSortIcon class="h-4 w-4 opacity-50" />
		</SelectIcon>
	</SelectTrigger>
</template>

// packages/svelte5/src/lib/components/ui/select/select-trigger.svelte
<script lang="ts">
	import { Select as SelectPrimitive, type WithoutChild } from "bits-ui";
	import CaretSort from "svelte-radix/CaretSort.svelte";
	import { cn } from "@kksh/svelte5/utils.ts";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithoutChild<SelectPrimitive.TriggerProps> = $props();
</script>

<SelectPrimitive.Trigger
	bind:ref
	class={cn(
		"border-input ring-offset-background placeholder:text-muted-foreground focus:ring-ring flex h-9 w-full items-center justify-between whitespace-nowrap rounded-md border bg-transparent px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-1 disabled:cursor-not-allowed disabled:opacity-50 [&>span]:line-clamp-1",
		className
	)}
	{...restProps}
>
	{@render children?.()}
	<CaretSort class="size-4 opacity-50" />
</SelectPrimitive.Trigger>
