// packages/vue/src/components/ui/skeleton/Skeleton.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

interface SkeletonProps {
	class?: HTMLAttributes["class"]
}

const props = defineProps<SkeletonProps>()
</script>

<template>
	<div :class="cn('bg-primary/10 animate-pulse rounded-md', props.class)" />
</template>

// packages/svelte5/src/lib/components/ui/skeleton/skeleton.svelte
<script lang="ts">
	import type { WithElementRef, WithoutChildren } from "bits-ui";
	import type { HTMLAttributes } from "svelte/elements";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: WithoutChildren<WithElementRef<HTMLAttributes<HTMLDivElement>>> = $props();
</script>

<div
	bind:this={ref}
	class={cn("bg-primary/10 animate-pulse rounded-md", className)}
	{...restProps}
></div>
