// packages/vue/src/components/ui/select/SelectLabel.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { SelectLabel, type SelectLabelProps } from "radix-vue"
import type { HTMLAttributes } from "vue"

const props = defineProps<SelectLabelProps & { class?: HTMLAttributes["class"] }>()
</script>

<template>
	<SelectLabel :class="cn('px-2 py-1.5 text-sm font-semibold', props.class)">
		<slot />
	</SelectLabel>
</template>

// packages/svelte/src/lib/components/ui/select/select-label.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Select as SelectPrimitive } from "bits-ui"

	type $$Props = SelectPrimitive.LabelProps

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<SelectPrimitive.Label class={cn("px-2 py-1.5 text-sm font-semibold", className)} {...$$restProps}>
	<slot />
</SelectPrimitive.Label>
