// packages/vue/src/components/ui/command/CommandInput.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { MagnifyingGlassIcon } from "@radix-icons/vue"
import { ComboboxInput, useForwardProps, type ComboboxInputProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

defineOptions({
	inheritAttrs: false
})

const props = defineProps<
	ComboboxInputProps & {
		class?: HTMLAttributes["class"]
	}
>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<div class="flex items-center border-b px-3" cmdk-input-wrapper>
		<MagnifyingGlassIcon class="mr-2 h-4 w-4 shrink-0 opacity-50" />
		<ComboboxInput
			v-bind="{ ...forwardedProps, ...$attrs }"
			auto-focus
			:class="
				cn(
					'placeholder:text-muted-foreground flex h-10 w-full rounded-md bg-transparent py-3 text-sm outline-none disabled:cursor-not-allowed disabled:opacity-50',
					props.class
				)
			"
		/>
	</div>
</template>

// packages/svelte5/src/lib/components/ui/command/command-input.svelte
<script lang="ts">
	import { Command as CommandPrimitive } from "bits-ui";
	import MagnifyingGlass from "svelte-radix/MagnifyingGlass.svelte";
	import { cn } from "@kksh/svelte5/utils.ts";

	let {
		ref = $bindable(null),
		class: className,
		value = $bindable(""),
		...restProps
	}: CommandPrimitive.InputProps = $props();
</script>

<div class="flex items-center border-b px-3" data-command-input-wrapper="">
	<MagnifyingGlass class="mr-2 size-4 shrink-0 opacity-50" />
	<CommandPrimitive.Input
		class={cn(
			"placeholder:text-muted-foreground flex h-10 w-full rounded-md bg-transparent py-3 text-sm outline-none disabled:cursor-not-allowed disabled:opacity-50",
			className
		)}
		bind:ref
		bind:value
		{...restProps}
	/>
</div>
