// packages/vue/src/components/ui/command/Command.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { ComboboxRootEmits, ComboboxRootProps } from "radix-vue"
import { ComboboxRoot, useForwardPropsEmits } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = withDefaults(defineProps<ComboboxRootProps & { class?: HTMLAttributes["class"] }>(), {
	open: true,
	modelValue: ""
})

const emits = defineEmits<ComboboxRootEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<ComboboxRoot
		v-bind="forwarded"
		:class="
			cn(
				'bg-popover text-popover-foreground flex h-full w-full flex-col overflow-hidden rounded-md',
				props.class
			)
		"
	>
		<slot />
	</ComboboxRoot>
</template>

// packages/svelte5/src/lib/components/ui/command/command.svelte
<script lang="ts">
	import { Command as CommandPrimitive } from "bits-ui";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		value = $bindable(""),
		ref = $bindable(null),
		class: className,
		...restProps
	}: CommandPrimitive.RootProps = $props();
</script>

<CommandPrimitive.Root
	class={cn(
		"bg-popover text-popover-foreground flex h-full w-full flex-col overflow-hidden rounded-md",
		className
	)}
	bind:ref
	bind:value
	{...restProps}
/>
