// packages/vue/src/components/ui/progress/Progress.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { ProgressIndicator, ProgressRoot, type ProgressRootProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = withDefaults(defineProps<ProgressRootProps & { class?: HTMLAttributes["class"] }>(), {
	modelValue: 0
})

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<ProgressRoot
		v-bind="delegatedProps"
		:class="cn('bg-primary/20 relative h-2 w-full overflow-hidden rounded-full', props.class)"
	>
		<ProgressIndicator
			class="bg-primary h-full w-full flex-1 transition-all"
			:style="`transform: translateX(-${100 - (props.modelValue ?? 0)}%);`"
		/>
	</ProgressRoot>
</template>

// packages/svelte/src/lib/components/ui/progress/progress.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Progress as ProgressPrimitive } from "bits-ui"

	type $$Props = ProgressPrimitive.Props

	let className: $$Props["class"] = undefined
	export let max: $$Props["max"] = 100
	export let value: $$Props["value"] = undefined
	export { className as class }
</script>

<ProgressPrimitive.Root
	class={cn("bg-primary/20 relative h-2 w-full overflow-hidden rounded-full", className)}
	{...$$restProps}
>
	<div
		class="bg-primary h-full w-full flex-1 transition-all"
		style={`transform: translateX(-${100 - (100 * (value ?? 0)) / (max ?? 1)}%)`}
	></div>
</ProgressPrimitive.Root>
