// packages/svelte/src/lib/components/ui/command/command-empty.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Command as CommandPrimitive } from "cmdk-sv"

	type $$Props = CommandPrimitive.EmptyProps
	let className: string | undefined | null = undefined
	export { className as class }
</script>

<CommandPrimitive.Empty class={cn("py-6 text-center text-sm", className)} {...$$restProps}>
	<slot />
</CommandPrimitive.Empty>

// packages/vue/src/components/ui/command/CommandEmpty.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { ComboboxEmptyProps } from "radix-vue"
import { ComboboxEmpty } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<ComboboxEmptyProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<ComboboxEmpty v-bind="delegatedProps" :class="cn('py-6 text-center text-sm', props.class)">
		<slot />
	</ComboboxEmpty>
</template>
