// packages/svelte/src/lib/components/ui/command/command-item.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Command as CommandPrimitive } from "cmdk-sv"

	type $$Props = CommandPrimitive.ItemProps

	export let asChild = false

	let className: string | undefined | null = undefined
	export { className as class }
</script>

<CommandPrimitive.Item
	{asChild}
	class={cn(
		"aria-selected:bg-accent aria-selected:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
		className
	)}
	{...$$restProps}
	let:action
	let:attrs
>
	<slot {action} {attrs} />
</CommandPrimitive.Item>

// packages/vue/src/components/ui/command/CommandItem.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { ComboboxItemEmits, ComboboxItemProps } from "radix-vue"
import { ComboboxItem, useForwardPropsEmits } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<ComboboxItemProps & { class?: HTMLAttributes["class"] }>()
const emits = defineEmits<ComboboxItemEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<ComboboxItem
		v-bind="forwarded"
		:class="
			cn(
				'data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
				props.class
			)
		"
	>
		<slot />
	</ComboboxItem>
</template>
