// packages/vue/src/components/ui/menubar/MenubarLabel.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { MenubarLabel, type MenubarLabelProps } from "radix-vue"
import type { HTMLAttributes } from "vue"

const props = defineProps<
	MenubarLabelProps & { class?: HTMLAttributes["class"]; inset?: boolean }
>()
</script>

<template>
	<MenubarLabel :class="cn('px-2 py-1.5 text-sm font-semibold', inset && 'pl-8', props.class)">
		<slot />
	</MenubarLabel>
</template>

// packages/svelte/src/lib/components/ui/menubar/menubar-label.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Menubar as MenubarPrimitive } from "bits-ui"

	type $$Props = MenubarPrimitive.LabelProps & {
		inset?: boolean
	}
	let className: $$Props["class"] = undefined
	export let inset: $$Props["inset"] = undefined
	export { className as class }
</script>

<MenubarPrimitive.Label
	class={cn("px-2 py-1.5 text-sm font-semibold", inset && "pl-8", className)}
	{...$$restProps}
>
	<slot />
</MenubarPrimitive.Label>
