// packages/vue/src/components/ui/menubar/MenubarCheckboxItem.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { CheckIcon } from "@radix-icons/vue"
import {
	MenubarCheckboxItem,
	MenubarItemIndicator,
	useForwardPropsEmits,
	type MenubarCheckboxItemEmits,
	type MenubarCheckboxItemProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<MenubarCheckboxItemProps & { class?: HTMLAttributes["class"] }>()
const emits = defineEmits<MenubarCheckboxItemEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<MenubarCheckboxItem
		v-bind="forwarded"
		:class="
			cn(
				'focus:bg-accent focus:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
				props.class
			)
		"
	>
		<span class="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
			<MenubarItemIndicator>
				<CheckIcon class="h-4 w-4" />
			</MenubarItemIndicator>
		</span>
		<slot />
	</MenubarCheckboxItem>
</template>

// packages/svelte/src/lib/components/ui/menubar/menubar-checkbox-item.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Menubar as MenubarPrimitive } from "bits-ui"
	import Check from "svelte-radix/Check.svelte"

	type $$Props = MenubarPrimitive.CheckboxItemProps
	let className: $$Props["class"] = undefined
	export { className as class }
	export let checked: $$Props["checked"] = undefined
</script>

<MenubarPrimitive.CheckboxItem
	bind:checked
	class={cn(
		"data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
		className
	)}
	{...$$restProps}
	on:click
	on:keydown
	on:focusin
	on:focusout
	on:pointerleave
	on:pointermove
	on:pointerdown
>
	<span class="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
		<MenubarPrimitive.CheckboxIndicator>
			<Check class="h-4 w-4" />
		</MenubarPrimitive.CheckboxIndicator>
	</span>
	<slot />
</MenubarPrimitive.CheckboxItem>
