// packages/vue/src/components/ui/menubar/MenubarTrigger.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { MenubarTrigger, useForwardProps, type MenubarTriggerProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<MenubarTriggerProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<MenubarTrigger
		v-bind="forwardedProps"
		:class="
			cn(
				'focus:bg-accent focus:text-accent-foreground data-[state=open]:bg-accent data-[state=open]:text-accent-foreground flex cursor-default select-none items-center rounded-sm px-3 py-1 text-sm font-medium outline-none',
				props.class
			)
		"
	>
		<slot />
	</MenubarTrigger>
</template>

// packages/svelte/src/lib/components/ui/menubar/menubar-trigger.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Menubar as MenubarPrimitive } from "bits-ui"

	type $$Props = MenubarPrimitive.TriggerProps
	type $$Events = MenubarPrimitive.TriggerEvents

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<MenubarPrimitive.Trigger
	class={cn(
		"focus:bg-accent focus:text-accent-foreground data-[state=open]:bg-accent data-[state=open]:text-accent-foreground flex cursor-default select-none items-center rounded-sm px-3 py-1 text-sm font-medium outline-none",
		className
	)}
	{...$$restProps}
	on:click
	on:keydown
	on:pointerenter
>
	<slot />
</MenubarPrimitive.Trigger>
