// packages/vue/src/components/ui/skeleton/Skeleton.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

interface SkeletonProps {
	class?: HTMLAttributes["class"]
}

const props = defineProps<SkeletonProps>()
</script>

<template>
	<div :class="cn('bg-primary/10 animate-pulse rounded-md', props.class)" />
</template>

// packages/svelte/src/lib/components/ui/skeleton/skeleton.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import type { HTMLAttributes } from "svelte/elements"

	type $$Props = HTMLAttributes<HTMLDivElement>

	let className: $$Props["class"] = undefined
	export { className as class }
</script>

<div class={cn("bg-primary/10 animate-pulse rounded-md", className)} {...$$restProps}></div>
