// packages/vue/src/components/ui/toggle/Toggle.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { Toggle, useForwardPropsEmits, type ToggleEmits, type ToggleProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"
import { toggleVariants, type ToggleVariants } from "."

const props = withDefaults(
	defineProps<
		ToggleProps & {
			class?: HTMLAttributes["class"]
			variant?: ToggleVariants["variant"]
			size?: ToggleVariants["size"]
		}
	>(),
	{
		variant: "default",
		size: "default",
		disabled: false
	}
)

const emits = defineEmits<ToggleEmits>()

const delegatedProps = computed(() => {
	const { class: _, size, variant, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<Toggle v-bind="forwarded" :class="cn(toggleVariants({ variant, size }), props.class)">
		<slot />
	</Toggle>
</template>

// packages/svelte/src/lib/components/ui/toggle/toggle.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { Toggle as TogglePrimitive } from "bits-ui"
	import { toggleVariants, type Size, type Variant } from "./index.js"

	type $$Props = TogglePrimitive.Props & {
		variant?: Variant
		size?: Size
	}
	type $$Events = TogglePrimitive.Events

	let className: $$Props["class"] = undefined
	export let variant: $$Props["variant"] = "default"
	export let size: $$Props["size"] = "default"
	export let pressed: $$Props["pressed"] = undefined
	export { className as class }
</script>

<TogglePrimitive.Root
	bind:pressed
	class={cn(toggleVariants({ variant, size, className }))}
	{...$$restProps}
	on:click
	on:keydown
>
	<slot />
</TogglePrimitive.Root>
