// packages/svelte5/src/lib/components/ui/range-calendar/range-calendar-header.svelte
<script lang="ts">
	import { RangeCalendar as RangeCalendarPrimitive } from "bits-ui";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: RangeCalendarPrimitive.HeaderProps = $props();
</script>

<RangeCalendarPrimitive.Header
	bind:ref
	class={cn("relative flex w-full items-center justify-between pt-1", className)}
	{...restProps}
/>

// packages/vue/src/components/ui/range-calendar/RangeCalendarHeader.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { RangeCalendarHeader, useForwardProps, type RangeCalendarHeaderProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<RangeCalendarHeaderProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<RangeCalendarHeader
		:class="cn('relative flex w-full items-center justify-between pt-1', props.class)"
		v-bind="forwardedProps"
	>
		<slot />
	</RangeCalendarHeader>
</template>
