// packages/vue/src/components/ui/range-calendar/RangeCalendarHeadCell.vue
<script lang="ts" setup>
import { cn } from "@/lib/utils"
import { RangeCalendarHeadCell, useForwardProps, type RangeCalendarHeadCellProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<RangeCalendarHeadCellProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<RangeCalendarHeadCell
		:class="cn('text-muted-foreground w-8 rounded-md text-[0.8rem] font-normal', props.class)"
		v-bind="forwardedProps"
	>
		<slot />
	</RangeCalendarHeadCell>
</template>

// packages/svelte5/src/lib/components/ui/range-calendar/range-calendar-head-cell.svelte
<script lang="ts">
	import { RangeCalendar as RangeCalendarPrimitive } from "bits-ui";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: RangeCalendarPrimitive.HeadCellProps = $props();
</script>

<RangeCalendarPrimitive.HeadCell
	bind:ref
	class={cn("text-muted-foreground w-8 rounded-md text-[0.8rem] font-normal", className)}
	{...restProps}
/>
