// packages/vue/src/components/ui/context-menu/ContextMenuSubTrigger.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { ChevronRightIcon } from "@radix-icons/vue"
import { ContextMenuSubTrigger, useForwardProps, type ContextMenuSubTriggerProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<
	ContextMenuSubTriggerProps & {
		class?: HTMLAttributes["class"]
		inset?: boolean
	}
>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
	<ContextMenuSubTrigger
		v-bind="forwardedProps"
		:class="
			cn(
				'focus:bg-accent focus:text-accent-foreground data-[state=open]:bg-accent data-[state=open]:text-accent-foreground flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none',
				inset && 'pl-8',
				props.class
			)
		"
	>
		<slot />
		<ChevronRightIcon class="ml-auto h-4 w-4" />
	</ContextMenuSubTrigger>
</template>

// packages/svelte/src/lib/components/ui/context-menu/context-menu-sub-trigger.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { ContextMenu as ContextMenuPrimitive } from "bits-ui"
	import ChevronRight from "svelte-radix/ChevronRight.svelte"

	type $$Props = ContextMenuPrimitive.SubTriggerProps & {
		inset?: boolean
	}
	type $$Events = ContextMenuPrimitive.SubTriggerEvents

	let className: $$Props["class"] = undefined
	export let inset: $$Props["inset"] = undefined
	export { className as class }
</script>

<ContextMenuPrimitive.SubTrigger
	class={cn(
		"data-[highlighted]:bg-accent data-[state=open]:bg-accent data-[highlighted]:text-accent-foreground data-[state=open]:text-accent-foreground flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none",
		inset && "pl-8",
		className
	)}
	{...$$restProps}
	on:click
	on:keydown
	on:focusin
	on:focusout
	on:pointerleave
	on:pointermove
>
	<slot />
	<ChevronRight class="ml-auto h-4 w-4" />
</ContextMenuPrimitive.SubTrigger>
