// packages/vue/src/components/ui/context-menu/ContextMenuItem.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import {
	ContextMenuItem,
	useForwardPropsEmits,
	type ContextMenuItemEmits,
	type ContextMenuItemProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<
	ContextMenuItemProps & { class?: HTMLAttributes["class"]; inset?: boolean }
>()
const emits = defineEmits<ContextMenuItemEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<ContextMenuItem
		v-bind="forwarded"
		:class="
			cn(
				'focus:bg-accent focus:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
				inset && 'pl-8',
				props.class
			)
		"
	>
		<slot />
	</ContextMenuItem>
</template>

// packages/svelte/src/lib/components/ui/context-menu/context-menu-item.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { ContextMenu as ContextMenuPrimitive } from "bits-ui"

	type $$Props = ContextMenuPrimitive.ItemProps & {
		inset?: boolean
	}
	type $$Events = ContextMenuPrimitive.ItemEvents

	let className: $$Props["class"] = undefined
	export let inset: $$Props["inset"] = undefined
	export { className as class }
</script>

<ContextMenuPrimitive.Item
	class={cn(
		"data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
		inset && "pl-8",
		className
	)}
	{...$$restProps}
	on:click
	on:keydown
	on:focusin
	on:focusout
	on:pointerdown
	on:pointerleave
	on:pointermove
>
	<slot />
</ContextMenuPrimitive.Item>
