// packages/vue/src/components/ui/context-menu/ContextMenuRadioItem.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { DotFilledIcon } from "@radix-icons/vue"
import {
	ContextMenuItemIndicator,
	ContextMenuRadioItem,
	useForwardPropsEmits,
	type ContextMenuRadioItemEmits,
	type ContextMenuRadioItemProps
} from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<ContextMenuRadioItemProps & { class?: HTMLAttributes["class"] }>()
const emits = defineEmits<ContextMenuRadioItemEmits>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
	<ContextMenuRadioItem
		v-bind="forwarded"
		:class="
			cn(
				'focus:bg-accent focus:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
				props.class
			)
		"
	>
		<span class="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
			<ContextMenuItemIndicator>
				<DotFilledIcon class="h-4 w-4 fill-current" />
			</ContextMenuItemIndicator>
		</span>
		<slot />
	</ContextMenuRadioItem>
</template>

// packages/svelte/src/lib/components/ui/context-menu/context-menu-radio-item.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { ContextMenu as ContextMenuPrimitive } from "bits-ui"
	import DotFilled from "svelte-radix/DotFilled.svelte"

	type $$Props = ContextMenuPrimitive.RadioItemProps
	type $$Events = ContextMenuPrimitive.RadioItemEvents

	let className: $$Props["class"] = undefined
	export let value: $$Props["value"]
	export { className as class }
</script>

<ContextMenuPrimitive.RadioItem
	class={cn(
		"data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
		className
	)}
	{value}
	{...$$restProps}
	on:click
	on:keydown
	on:focusin
	on:focusout
	on:pointerdown
	on:pointerleave
	on:pointermove
>
	<span class="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
		<ContextMenuPrimitive.RadioIndicator>
			<DotFilled class="h-4 w-4 fill-current" />
		</ContextMenuPrimitive.RadioIndicator>
	</span>
	<slot />
</ContextMenuPrimitive.RadioItem>
