// packages/vue/src/components/ui/context-menu/ContextMenuLabel.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { ContextMenuLabel, type ContextMenuLabelProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<
	ContextMenuLabelProps & { class?: HTMLAttributes["class"]; inset?: boolean }
>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<ContextMenuLabel
		v-bind="delegatedProps"
		:class="cn('text-foreground px-2 py-1.5 text-sm font-semibold', inset && 'pl-8', props.class)"
	>
		<slot />
	</ContextMenuLabel>
</template>

// packages/svelte/src/lib/components/ui/context-menu/context-menu-label.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js"
	import { ContextMenu as ContextMenuPrimitive } from "bits-ui"

	type $$Props = ContextMenuPrimitive.LabelProps & {
		inset?: boolean
	}

	let className: $$Props["class"] = undefined
	export let inset: $$Props["inset"] = undefined
	export { className as class }
</script>

<ContextMenuPrimitive.Label
	class={cn("text-foreground px-2 py-1.5 text-sm font-semibold", inset && "pl-8", className)}
	{...$$restProps}
>
	<slot />
</ContextMenuPrimitive.Label>
