// packages/svelte5/src/lib/components/ui/label/label.svelte
<script lang="ts">
	import { Label as LabelPrimitive } from "bits-ui";
	import { cn } from "@kksh/svelte5/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: LabelPrimitive.RootProps = $props();
</script>

<LabelPrimitive.Root
	bind:ref
	class={cn(
		"text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
		className
	)}
	{...restProps}
/>

// packages/vue/src/components/ui/label/Label.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { Label, type LabelProps } from "radix-vue"
import { computed, type HTMLAttributes } from "vue"

const props = defineProps<LabelProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = computed(() => {
	const { class: _, ...delegated } = props

	return delegated
})
</script>

<template>
	<Label
		v-bind="delegatedProps"
		:class="
			cn(
				'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
				props.class
			)
		"
	>
		<slot />
	</Label>
</template>
