// packages/vue/src/App.vue
<script setup lang="ts">
import { Alert } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { $themeConfig, ThemeConfig, updateTheme } from "@/stores/config"
import { useStore } from "@nanostores/vue"
import { onMounted, reactive, watch } from "vue"
import ThemeCustomizer from "./components/theme/ThemeCustomizer.vue"

const themeConfigStore = useStore($themeConfig)
const themeConfig = reactive<ThemeConfig>({
	theme: "neutral",
	radius: 0.5,
	lightMode: "auto"
})
onMounted(() => {
	themeConfig.lightMode = themeConfigStore.value.lightMode
	themeConfig.theme = themeConfigStore.value.theme
	themeConfig.radius = themeConfigStore.value.radius
})

watch(themeConfig, (newThemeConfig) => {
	updateTheme(newThemeConfig)
})
</script>

<template>
	<Button>Hello</Button>
	<Alert>Alert</Alert>
	<pre>{{ themeConfig }}</pre>
	<ThemeCustomizer
		v-model:lightMode="themeConfig.lightMode"
		v-model:theme="themeConfig.theme"
		v-model:radius="themeConfig.radius"
	/>
</template>

// apps/svelte/src/App.svelte
<script lang="ts">
	import "./app.css"
	import {
		Button,
		ModeDropdown,
		ModeToggle,
		themeConfigStore,
		ThemeCustomizer,
		ThemeWrapper,
		updateTheme,
		type ThemeConfig
	} from "@shadcn-components/svelte"
	import { ModeWatcher } from "mode-watcher"
	import { get } from "svelte/store"

	// init this config with persisted data from a persisted store in production, this is just a demo
	let config: ThemeConfig = {
		radius: get(themeConfigStore).radius,
		theme: get(themeConfigStore).theme,
		lightMode: get(themeConfigStore).lightMode
	}

	$: updateTheme(config)
</script>

<ModeWatcher />
<ThemeWrapper>
	<pre>{JSON.stringify(config, null, 2)}</pre>
	<ThemeCustomizer bind:config />
	<Button>Hello</Button>
	<ModeToggle />
</ThemeWrapper>
